/**
 * Auto-generated compound rules (Q)
 * Source: LanguageTool compounds.txt
 * Generated: 2026-01-28T19:51:36.712Z
 * 
 * These rules detect split compound words that should be joined.
 * 
 * DO NOT EDIT - Generated by convert-compounds.cjs
 */

import type { GrammarRule } from '../../../types';

export const compoundRulesQ: GrammarRule[] = [
  {
    id: 'compound_quarterhour_1246',
    name: 'quarterhour compound',
    description: 'Compound word: quarter-hour',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+hour\b/gi,
    message: '"quarter hour" should be written as "quarter-hour".',
    suggestions: () => ['quarter-hour'],
  },
  {
    id: 'compound_quarterlight_1247',
    name: 'quarterlight compound',
    description: 'Compound word: quarter-light',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+light\b/gi,
    message: '"quarter light" should be written as "quarter-light".',
    suggestions: () => ['quarter-light'],
  },
  {
    id: 'compound_quasisynchronous_1248',
    name: 'quasisynchronous compound',
    description: 'Compound word: quasi-synchronous',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquasi\s+synchronous\b/gi,
    message: '"quasi synchronous" should be written as "quasi-synchronous".',
    suggestions: () => ['quasi-synchronous'],
  },
  {
    id: 'compound_queuejump_1249',
    name: 'queuejump compound',
    description: 'Compound word: queue-jump',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bqueue\s+jump\b/gi,
    message: '"queue jump" should be written as "queue-jump".',
    suggestions: () => ['queue-jump'],
  },
  {
    id: 'compound_queuejumping_1250',
    name: 'queuejumping compound',
    description: 'Compound word: queue-jumping',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bqueue\s+jumping\b/gi,
    message: '"queue jumping" should be written as "queue-jumping".',
    suggestions: () => ['queue-jumping'],
  },
  {
    id: 'compound_quickwitted_1251',
    name: 'quickwitted compound',
    description: 'Compound word: quick-witted',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquick\s+witted\b/gi,
    message: '"quick witted" should be written as "quick-witted".',
    suggestions: () => ['quick-witted'],
  },
  {
    id: 'compound_quarterfinal_2731',
    name: 'quarterfinal compound',
    description: 'Compound word: quarter-final',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+final\b/gi,
    message: '"quarter final" should be written as "quarter-final".',
    suggestions: () => ['quarterfinal'],
  },
  {
    id: 'compound_quarterfinals_2732',
    name: 'quarterfinals compound',
    description: 'Compound word: quarter-finals',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+finals\b/gi,
    message: '"quarter finals" should be written as "quarter-finals".',
    suggestions: () => ['quarterfinals'],
  },
  {
    id: 'compound_queensized_4688',
    name: 'queensized compound',
    description: 'Compound word: queen-sized',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bqueen\s+sized\b/gi,
    message: '"queen sized" should be written as "queen-sized".',
    suggestions: () => ['queen-sized'],
  },
  {
    id: 'compound_quicksightedness_5185',
    name: 'quicksightedness compound',
    description: 'Compound word: quick-sightedness',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquick\s+sightedness\b/gi,
    message: '"quick sightedness" should be written as "quick-sightedness".',
    suggestions: () => ['quick-sightedness'],
  },
  {
    id: 'compound_quadcore_7030',
    name: 'quadcore compound',
    description: 'Compound word: quad-core',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquad\s+core\b/gi,
    message: '"quad core" should be written as "quad-core".',
    suggestions: () => ['quad-core'],
  },
  {
    id: 'compound_quartercentury_8062',
    name: 'quartercentury compound',
    description: 'Compound word: quarter-century',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+century\b/gi,
    message: '"quarter century" should be written as "quarter-century".',
    suggestions: () => ['quarter-century'],
  },
  {
    id: 'compound_quartercenturies_8063',
    name: 'quartercenturies compound',
    description: 'Compound word: quarter-centuries',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bquarter\s+centuries\b/gi,
    message: '"quarter centuries" should be written as "quarter-centuries".',
    suggestions: () => ['quarter-centuries'],
  }
];
