/**
 * Auto-generated compound rules (Y)
 * Source: LanguageTool compounds.txt
 * Generated: 2026-01-28T19:51:36.714Z
 * 
 * These rules detect split compound words that should be joined.
 * 
 * DO NOT EDIT - Generated by convert-compounds.cjs
 */

import type { GrammarRule } from '../../../types';

export const compoundRulesY: GrammarRule[] = [
  {
    id: 'compound_yaxis_1899',
    name: 'yaxis compound',
    description: 'Compound word: y-axis',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\by\s+axis\b/gi,
    message: '"y axis" should be written as "y-axis".',
    suggestions: () => ['y-axis'],
  },
  {
    id: 'compound_yearend_1900',
    name: 'yearend compound',
    description: 'Compound word: year-end',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\byear\s+end\b/gi,
    message: '"year end" should be written as "year-end".',
    suggestions: () => ['year-end'],
  },
  {
    id: 'compound_yearonyear_1901',
    name: 'yearonyear compound',
    description: 'Compound word: year-on-year',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\byear\s+on\s+year\b/gi,
    message: '"year on year" should be written as "year-on-year".',
    suggestions: () => ['year-on-year'],
  },
  {
    id: 'compound_yellowbellied_1902',
    name: 'yellowbellied compound',
    description: 'Compound word: yellow-bellied',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\byellow\s+bellied\b/gi,
    message: '"yellow bellied" should be written as "yellow-bellied".',
    suggestions: () => ['yellow-bellied'],
  },
  {
    id: 'compound_Yojong_5377',
    name: 'Yojong compound',
    description: 'Compound word: Yo-jong',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bYo\s+jong\b/gi,
    message: '"Yo jong" should be written as "Yo-jong".',
    suggestions: () => ['Yojong'],
  }
];
