/**
 * Auto-generated compound rules (X)
 * Source: LanguageTool compounds.txt
 * Generated: 2026-01-28T19:51:36.714Z
 * 
 * These rules detect split compound words that should be joined.
 * 
 * DO NOT EDIT - Generated by convert-compounds.cjs
 */

import type { GrammarRule } from '../../../types';

export const compoundRulesX: GrammarRule[] = [
  {
    id: 'compound_xaxis_1894',
    name: 'xaxis compound',
    description: 'Compound word: x-axis',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bx\s+axis\b/gi,
    message: '"x axis" should be written as "x-axis".',
    suggestions: () => ['x-axis'],
  },
  {
    id: 'compound_xray_1895',
    name: 'xray compound',
    description: 'Compound word: x-ray',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bx\s+ray\b/gi,
    message: '"x ray" should be written as "x-ray".',
    suggestions: () => ['x-ray'],
  },
  {
    id: 'compound_xrays_1896',
    name: 'xrays compound',
    description: 'Compound word: x-rays',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bx\s+rays\b/gi,
    message: '"x rays" should be written as "x-rays".',
    suggestions: () => ['x-rays'],
  },
  {
    id: 'compound_xrayed_1897',
    name: 'xrayed compound',
    description: 'Compound word: x-rayed',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bx\s+rayed\b/gi,
    message: '"x rayed" should be written as "x-rayed".',
    suggestions: () => ['x-rayed'],
  },
  {
    id: 'compound_xraying_1898',
    name: 'xraying compound',
    description: 'Compound word: x-raying',
    category: 'compounds',
    severity: 'suggestion' as const,
    pattern: /\bx\s+raying\b/gi,
    message: '"x raying" should be written as "x-raying".',
    suggestions: () => ['x-raying'],
  }
];
