/**
 * Auto-generated confusion rules (W)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.516Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesW: GrammarRule[] = [
  {
    id: 'confusion_won_own_486',
    name: 'won vs own',
    description: 'Commonly confused words: won and own',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwon\b/gi,
    message: 'Did you mean "own"? "won" ("won") is often confused with "own" ("own").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'own';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wade_weighed_716',
    name: 'wade vs weighed',
    description: 'Commonly confused words: wade and weighed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwade\b/gi,
    message: 'Check: "wade" ("wade") vs "weighed" ("weighed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'weighed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wades_weights_717',
    name: 'wades vs weights',
    description: 'Commonly confused words: wades and weights',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwades\b/gi,
    message: 'Check: "wades" ("wades") vs "weights" ("weights"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'weights';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waist_waste_718',
    name: 'waist vs waste',
    description: 'Commonly confused words: waist and waste',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaist\b/gi,
    message: 'Check: "waist" (midsection) vs "waste" (unused material). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waste';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waists_wastes_719',
    name: 'waists vs wastes',
    description: 'Commonly confused words: waists and wastes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaists\b/gi,
    message: 'Check: "waists" ("waists") vs "wastes" ("wastes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wastes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weighted_waited_720',
    name: 'weighted vs waited',
    description: 'Commonly confused words: weighted and waited',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweighted\b/gi,
    message: 'Did you mean "waited"? "weighted" ("weighted") is often confused with "waited" ("waited").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waited';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waive_wave_721',
    name: 'waive vs wave',
    description: 'Commonly confused words: waive and wave',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaive\b/gi,
    message: 'Check: "waive" ("waive") vs "wave" ("wave"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wave';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waives_waves_722',
    name: 'waives vs waves',
    description: 'Commonly confused words: waives and waves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaives\b/gi,
    message: 'Check: "waives" ("waives") vs "waves" ("waves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wandered_wondered_723',
    name: 'wandered vs wondered',
    description: 'Commonly confused words: wandered and wondered',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwandered\b/gi,
    message: 'Check: "wandered" ("wandered") vs "wondered" ("wondered"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wondered';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wandering_wondering_724',
    name: 'wandering vs wondering',
    description: 'Commonly confused words: wandering and wondering',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwandering\b/gi,
    message: 'Check: "wandering" ("wandering") vs "wondering" ("wondering"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wondering';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wanders_wonders_725',
    name: 'wanders vs wonders',
    description: 'Commonly confused words: wanders and wonders',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwanders\b/gi,
    message: 'Check: "wanders" ("wanders") vs "wonders" ("wonders"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wonders';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wander_wonder_726',
    name: 'wander vs wonder',
    description: 'Commonly confused words: wander and wonder',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwander\b/gi,
    message: 'Check: "wander" ("wander") vs "wonder" ("wonder"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wonder';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wand_want_727',
    name: 'wand vs want',
    description: 'Commonly confused words: wand and want',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwand\b/gi,
    message: 'Check: "wand" ("wand") vs "want" ("want"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'want';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_war_wore_728',
    name: 'war vs wore',
    description: 'Commonly confused words: war and wore',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwar\b/gi,
    message: 'Check: "war" ("war") vs "wore" ("wore"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wore';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warming_warning_729',
    name: 'warming vs warning',
    description: 'Commonly confused words: warming and warning',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarming\b/gi,
    message: 'Check: "warming" ("warming") vs "warning" ("warning"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warning';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warm_warn_730',
    name: 'warm vs warn',
    description: 'Commonly confused words: warm and warn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarm\b/gi,
    message: 'Check: "warm" ("warm") vs "warn" ("warn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warms_warns_731',
    name: 'warms vs warns',
    description: 'Commonly confused words: warms and warns',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarms\b/gi,
    message: 'Check: "warms" ("warms") vs "warns" ("warns"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warns';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warn_worn_732',
    name: 'warn vs worn',
    description: 'Commonly confused words: warn and worn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarn\b/gi,
    message: 'Check: "warn" ("warn") vs "worn" ("worn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'worn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warship_worship_733',
    name: 'warship vs worship',
    description: 'Commonly confused words: warship and worship',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarship\b/gi,
    message: 'Check: "warship" ("warship") vs "worship" ("worship"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'worship';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wary_wherry_734',
    name: 'wary vs wherry',
    description: 'Commonly confused words: wary and wherry',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwary\b/gi,
    message: 'Check: "wary" ("wary") vs "wherry" ("wherry"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wherry';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_was_way_735',
    name: 'was vs way',
    description: 'Commonly confused words: was and way',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwas\b/gi,
    message: 'Check: "was" ("was") vs "way" ("way"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'way';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_watt_what_736',
    name: 'watt vs what',
    description: 'Commonly confused words: watt and what',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwatt\b/gi,
    message: 'Check: "watt" ("watt") vs "what" ("what"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'what';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_way_wax_737',
    name: 'way vs wax',
    description: 'Commonly confused words: way and wax',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bway\b/gi,
    message: 'Did you mean "wax"? "way" ("way") is often confused with "wax" ("wax").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wax';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wax_way_738',
    name: 'wax vs way',
    description: 'Commonly confused words: wax and way',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwax\b/gi,
    message: 'Did you mean "way"? "wax" ("wax") is often confused with "way" ("way").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'way';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weak_week_739',
    name: 'weak vs week',
    description: 'Commonly confused words: weak and week',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweak\b/gi,
    message: 'Check: "weak" (not strong) vs "week" (seven days). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'week';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whether_weather_740',
    name: 'whether vs weather',
    description: 'Commonly confused words: whether and weather',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhether\b/gi,
    message: 'Did you mean "weather"? "whether" (if (conjunction)) is often confused with "weather" (atmospheric conditions).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'weather';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weather_whether_741',
    name: 'weather vs whether',
    description: 'Commonly confused words: weather and whether',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweather\b/gi,
    message: 'Did you mean "whether"? "weather" (atmospheric conditions) is often confused with "whether" (if (conjunction)).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whether';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weigh_whey_742',
    name: 'weigh vs whey',
    description: 'Commonly confused words: weigh and whey',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweigh\b/gi,
    message: 'Check: "weigh" ("weigh") vs "whey" ("whey"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whey';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weld_welled_743',
    name: 'weld vs welled',
    description: 'Commonly confused words: weld and welled',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweld\b/gi,
    message: 'Check: "weld" ("weld") vs "welled" ("welled"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'welled';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wee_we_744',
    name: 'wee vs we',
    description: 'Commonly confused words: wee and we',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwee\b/gi,
    message: 'Did you mean "we"? "wee" ("wee") is often confused with "we" ("we").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'we';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_where_were_745',
    name: 'where vs were',
    description: 'Commonly confused words: where and were',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhere\b/gi,
    message: 'Did you mean "were"? "where" (at what place) is often confused with "were" ("were").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'were';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wheeled_wield_746',
    name: 'wheeled vs wield',
    description: 'Commonly confused words: wheeled and wield',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwheeled\b/gi,
    message: 'Check: "wheeled" ("wheeled") vs "wield" ("wield"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wield';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_which_witch_747',
    name: 'which vs witch',
    description: 'Commonly confused words: which and witch',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhich\b/gi,
    message: 'Check: "which" ("which") vs "witch" ("witch"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'witch';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whiled_wild_748',
    name: 'whiled vs wild',
    description: 'Commonly confused words: whiled and wild',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhiled\b/gi,
    message: 'Check: "whiled" ("whiled") vs "wild" ("wild"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wild';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_while_whole_749',
    name: 'while vs whole',
    description: 'Commonly confused words: while and whole',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhile\b/gi,
    message: 'Did you mean "whole"? "while" ("while") is often confused with "whole" (entire).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whole';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whole_while_750',
    name: 'whole vs while',
    description: 'Commonly confused words: whole and while',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhole\b/gi,
    message: 'Did you mean "while"? "whole" (entire) is often confused with "while" ("while").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'while';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whirred_word_751',
    name: 'whirred vs word',
    description: 'Commonly confused words: whirred and word',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhirred\b/gi,
    message: 'Check: "whirred" ("whirred") vs "word" ("word"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'word';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_widow_window_752',
    name: 'widow vs window',
    description: 'Commonly confused words: widow and window',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwidow\b/gi,
    message: 'Check: "widow" ("widow") vs "window" ("window"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'window';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wit_with_753',
    name: 'wit vs with',
    description: 'Commonly confused words: wit and with',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwit\b/gi,
    message: 'Check: "wit" ("wit") vs "with" ("with"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'with';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_woman_women_754',
    name: 'woman vs women',
    description: 'Commonly confused words: woman and women',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwoman\b/gi,
    message: 'Check: "woman" ("woman") vs "women" ("women"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'women';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_worse_worth_755',
    name: 'worse vs worth',
    description: 'Commonly confused words: worse and worth',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bworse\b/gi,
    message: 'Check: "worse" ("worse") vs "worth" ("worth"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'worth';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wright_write_756',
    name: 'wright vs write',
    description: 'Commonly confused words: wright and write',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwright\b/gi,
    message: 'Check: "wright" ("wright") vs "write" (to put words on paper). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'write';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wring_wrong_757',
    name: 'wring vs wrong',
    description: 'Commonly confused words: wring and wrong',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwring\b/gi,
    message: 'Check: "wring" ("wring") vs "wrong" ("wrong"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wrong';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wrings_wrongs_758',
    name: 'wrings vs wrongs',
    description: 'Commonly confused words: wrings and wrongs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwrings\b/gi,
    message: 'Check: "wrings" ("wrings") vs "wrongs" ("wrongs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wrongs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whit_with_780',
    name: 'whit vs with',
    description: 'Commonly confused words: whit and with',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhit\b/gi,
    message: 'Did you mean "with"? "whit" ("whit") is often confused with "with" ("with").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'with';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_which_wish_790',
    name: 'which vs wish',
    description: 'Commonly confused words: which and wish',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhich\b/gi,
    message: 'Check: "which" ("which") vs "wish" ("wish"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wish';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_write_wrote_791',
    name: 'write vs wrote',
    description: 'Commonly confused words: write and wrote',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwrite\b/gi,
    message: 'Check: "write" (to put words on paper) vs "wrote" ("wrote"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wrote';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waders_wafers_4242',
    name: 'waders vs wafers',
    description: 'Commonly confused words: waders and wafers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaders\b/gi,
    message: 'Check: "waders" ("waders") vs "wafers" ("wafers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wafers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wafers_wavers_4243',
    name: 'wafers vs wavers',
    description: 'Commonly confused words: wafers and wavers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwafers\b/gi,
    message: 'Check: "wafers" ("wafers") vs "wavers" ("wavers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wavers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wafer_waver_4244',
    name: 'wafer vs waver',
    description: 'Commonly confused words: wafer and waver',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwafer\b/gi,
    message: 'Check: "wafer" ("wafer") vs "waver" ("waver"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waver';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waffled_waffles_4245',
    name: 'waffled vs waffles',
    description: 'Commonly confused words: waffled and waffles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaffled\b/gi,
    message: 'Check: "waffled" ("waffled") vs "waffles" ("waffles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waffles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wafts_warts_4246',
    name: 'wafts vs warts',
    description: 'Commonly confused words: wafts and warts',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwafts\b/gi,
    message: 'Check: "wafts" ("wafts") vs "warts" ("warts"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warts';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waged_wages_4247',
    name: 'waged vs wages',
    description: 'Commonly confused words: waged and wages',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaged\b/gi,
    message: 'Check: "waged" ("waged") vs "wages" ("wages"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wages';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wager_eager_4248',
    name: 'wager vs eager',
    description: 'Commonly confused words: wager and eager',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwager\b/gi,
    message: 'Check: "wager" ("wager") vs "eager" ("eager"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'eager';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wages_sages_4249',
    name: 'wages vs sages',
    description: 'Commonly confused words: wages and sages',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwages\b/gi,
    message: 'Check: "wages" ("wages") vs "sages" ("sages"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sages';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wagged_sagged_4250',
    name: 'wagged vs sagged',
    description: 'Commonly confused words: wagged and sagged',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwagged\b/gi,
    message: 'Check: "wagged" ("wagged") vs "sagged" ("sagged"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sagged';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wagging_sagging_4251',
    name: 'wagging vs sagging',
    description: 'Commonly confused words: wagging and sagging',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwagging\b/gi,
    message: 'Check: "wagging" ("wagging") vs "sagging" ("sagging"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sagging';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wailed_sailed_4252',
    name: 'wailed vs sailed',
    description: 'Commonly confused words: wailed and sailed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwailed\b/gi,
    message: 'Check: "wailed" ("wailed") vs "sailed" ("sailed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sailed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waived_waives_4253',
    name: 'waived vs waives',
    description: 'Commonly confused words: waived and waives',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaived\b/gi,
    message: 'Check: "waived" ("waived") vs "waives" ("waives"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waives';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_walked_walled_4254',
    name: 'walked vs walled',
    description: 'Commonly confused words: walked and walled',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwalked\b/gi,
    message: 'Check: "walked" ("walked") vs "walled" ("walled"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'walled';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waltzed_waltzes_4255',
    name: 'waltzed vs waltzes',
    description: 'Commonly confused words: waltzed and waltzes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaltzed\b/gi,
    message: 'Check: "waltzed" ("waltzed") vs "waltzes" ("waltzes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'waltzes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wander_sander_4256',
    name: 'wander vs sander',
    description: 'Commonly confused words: wander and sander',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwander\b/gi,
    message: 'Check: "wander" ("wander") vs "sander" ("sander"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sander';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wands_wanes_4257',
    name: 'wands vs wanes',
    description: 'Commonly confused words: wands and wanes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwands\b/gi,
    message: 'Check: "wands" ("wands") vs "wanes" ("wanes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wanes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waned_wanes_4258',
    name: 'waned vs wanes',
    description: 'Commonly confused words: waned and wanes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaned\b/gi,
    message: 'Check: "waned" ("waned") vs "wanes" ("wanes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wanes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warehoused_warehouses_4259',
    name: 'warehoused vs warehouses',
    description: 'Commonly confused words: warehoused and warehouses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarehoused\b/gi,
    message: 'Check: "warehoused" ("warehoused") vs "warehouses" ("warehouses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warehouses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warmed_warned_4260',
    name: 'warmed vs warned',
    description: 'Commonly confused words: warmed and warned',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarmed\b/gi,
    message: 'Check: "warmed" ("warmed") vs "warned" ("warned"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warned';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warn_earn_4261',
    name: 'warn vs earn',
    description: 'Commonly confused words: warn and earn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarn\b/gi,
    message: 'Check: "warn" ("warn") vs "earn" ("earn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'earn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_warrantied_warranties_4262',
    name: 'warrantied vs warranties',
    description: 'Commonly confused words: warrantied and warranties',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwarrantied\b/gi,
    message: 'Check: "warrantied" ("warrantied") vs "warranties" ("warranties"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'warranties';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_waver_saver_4263',
    name: 'waver vs saver',
    description: 'Commonly confused words: waver and saver',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwaver\b/gi,
    message: 'Check: "waver" ("waver") vs "saver" ("saver"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'saver';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wavers_savers_4264',
    name: 'wavers vs savers',
    description: 'Commonly confused words: wavers and savers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwavers\b/gi,
    message: 'Check: "wavers" ("wavers") vs "savers" ("savers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'savers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_webs_wens_4265',
    name: 'webs vs wens',
    description: 'Commonly confused words: webs and wens',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwebs\b/gi,
    message: 'Check: "webs" ("webs") vs "wens" ("wens"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wens';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wedded_weeded_4266',
    name: 'wedded vs weeded',
    description: 'Commonly confused words: wedded and weeded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwedded\b/gi,
    message: 'Check: "wedded" ("wedded") vs "weeded" ("weeded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'weeded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wedged_wedges_4267',
    name: 'wedged vs wedges',
    description: 'Commonly confused words: wedged and wedges',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwedged\b/gi,
    message: 'Check: "wedged" ("wedged") vs "wedges" ("wedges"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wedges';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weeded_seeded_4268',
    name: 'weeded vs seeded',
    description: 'Commonly confused words: weeded and seeded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweeded\b/gi,
    message: 'Check: "weeded" ("weeded") vs "seeded" ("seeded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seeded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weeding_seeding_4269',
    name: 'weeding vs seeding',
    description: 'Commonly confused words: weeding and seeding',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweeding\b/gi,
    message: 'Check: "weeding" ("weeding") vs "seeding" ("seeding"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seeding';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_week_seek_4270',
    name: 'week vs seek',
    description: 'Commonly confused words: week and seek',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweek\b/gi,
    message: 'Check: "week" (seven days) vs "seek" ("seek"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seek';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weeks_seeks_4271',
    name: 'weeks vs seeks',
    description: 'Commonly confused words: weeks and seeks',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweeks\b/gi,
    message: 'Check: "weeks" ("weeks") vs "seeks" ("seeks"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seeks';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weep_seep_4272',
    name: 'weep vs seep',
    description: 'Commonly confused words: weep and seep',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweep\b/gi,
    message: 'Check: "weep" ("weep") vs "seep" ("seep"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seep';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weeps_seeps_4273',
    name: 'weeps vs seeps',
    description: 'Commonly confused words: weeps and seeps',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweeps\b/gi,
    message: 'Check: "weeps" ("weeps") vs "seeps" ("seeps"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'seeps';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wees_sees_4274',
    name: 'wees vs sees',
    description: 'Commonly confused words: wees and sees',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwees\b/gi,
    message: 'Check: "wees" ("wees") vs "sees" ("sees"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sees';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_weight_wright_4275',
    name: 'weight vs wright',
    description: 'Commonly confused words: weight and wright',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bweight\b/gi,
    message: 'Check: "weight" (heaviness) vs "wright" ("wright"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wright';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wending_sending_4276',
    name: 'wending vs sending',
    description: 'Commonly confused words: wending and sending',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwending\b/gi,
    message: 'Check: "wending" ("wending") vs "sending" ("sending"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sending';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wends_sends_4277',
    name: 'wends vs sends',
    description: 'Commonly confused words: wends and sends',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwends\b/gi,
    message: 'Check: "wends" ("wends") vs "sends" ("sends"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sends';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wetter_setter_4278',
    name: 'wetter vs setter',
    description: 'Commonly confused words: wetter and setter',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwetter\b/gi,
    message: 'Check: "wetter" ("wetter") vs "setter" ("setter"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'setter';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whacking_shacking_4279',
    name: 'whacking vs shacking',
    description: 'Commonly confused words: whacking and shacking',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhacking\b/gi,
    message: 'Check: "whacking" ("whacking") vs "shacking" ("shacking"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shacking';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whacks_shacks_4280',
    name: 'whacks vs shacks',
    description: 'Commonly confused words: whacks and shacks',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhacks\b/gi,
    message: 'Check: "whacks" ("whacks") vs "shacks" ("shacks"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shacks';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whale_shale_4281',
    name: 'whale vs shale',
    description: 'Commonly confused words: whale and shale',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhale\b/gi,
    message: 'Check: "whale" ("whale") vs "shale" ("shale"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shale';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wherein_whereon_4282',
    name: 'wherein vs whereon',
    description: 'Commonly confused words: wherein and whereon',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwherein\b/gi,
    message: 'Check: "wherein" ("wherein") vs "whereon" ("whereon"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whereon';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whet_whey_4283',
    name: 'whet vs whey',
    description: 'Commonly confused words: whet and whey',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhet\b/gi,
    message: 'Check: "whet" ("whet") vs "whey" ("whey"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whey';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whiled_whiles_4284',
    name: 'whiled vs whiles',
    description: 'Commonly confused words: whiled and whiles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhiled\b/gi,
    message: 'Check: "whiled" ("whiled") vs "whiles" ("whiles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whiles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whim_shim_4285',
    name: 'whim vs shim',
    description: 'Commonly confused words: whim and shim',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhim\b/gi,
    message: 'Check: "whim" ("whim") vs "shim" ("shim"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shim';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whims_shims_4286',
    name: 'whims vs shims',
    description: 'Commonly confused words: whims and shims',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhims\b/gi,
    message: 'Check: "whims" ("whims") vs "shims" ("shims"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shims';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whim_whom_4287',
    name: 'whim vs whom',
    description: 'Commonly confused words: whim and whom',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhim\b/gi,
    message: 'Check: "whim" ("whim") vs "whom" ("whom"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whom';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whipping_whopping_4288',
    name: 'whipping vs whopping',
    description: 'Commonly confused words: whipping and whopping',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhipping\b/gi,
    message: 'Check: "whipping" ("whipping") vs "whopping" ("whopping"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whopping';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whirls_whorls_4289',
    name: 'whirls vs whorls',
    description: 'Commonly confused words: whirls and whorls',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhirls\b/gi,
    message: 'Check: "whirls" ("whirls") vs "whorls" ("whorls"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whorls';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whirl_whorl_4290',
    name: 'whirl vs whorl',
    description: 'Commonly confused words: whirl and whorl',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhirl\b/gi,
    message: 'Check: "whirl" ("whirl") vs "whorl" ("whorl"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whorl';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whistled_whistles_4291',
    name: 'whistled vs whistles',
    description: 'Commonly confused words: whistled and whistles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhistled\b/gi,
    message: 'Check: "whistled" ("whistled") vs "whistles" ("whistles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whistles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whited_whites_4292',
    name: 'whited vs whites',
    description: 'Commonly confused words: whited and whites',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhited\b/gi,
    message: 'Check: "whited" ("whited") vs "whites" ("whites"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whites';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whittled_whittles_4293',
    name: 'whittled vs whittles',
    description: 'Commonly confused words: whittled and whittles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhittled\b/gi,
    message: 'Check: "whittled" ("whittled") vs "whittles" ("whittles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whittles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whooped_whoopee_4294',
    name: 'whooped vs whoopee',
    description: 'Commonly confused words: whooped and whoopee',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhooped\b/gi,
    message: 'Check: "whooped" ("whooped") vs "whoopee" ("whoopee"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whoopee';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whooper_whoopee_4295',
    name: 'whooper vs whoopee',
    description: 'Commonly confused words: whooper and whoopee',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhooper\b/gi,
    message: 'Check: "whooper" ("whooper") vs "whoopee" ("whoopee"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whoopee';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whooper_whopper_4296',
    name: 'whooper vs whopper',
    description: 'Commonly confused words: whooper and whopper',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhooper\b/gi,
    message: 'Check: "whooper" ("whooper") vs "whopper" ("whopper"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whopper';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whoring_shoring_4297',
    name: 'whoring vs shoring',
    description: 'Commonly confused words: whoring and shoring',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhoring\b/gi,
    message: 'Check: "whoring" ("whoring") vs "shoring" ("shoring"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'shoring';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_whup_whip_4298',
    name: 'whup vs whip',
    description: 'Commonly confused words: whup and whip',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwhup\b/gi,
    message: 'Check: "whup" ("whup") vs "whip" ("whip"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'whip';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wickers_wickets_4299',
    name: 'wickers vs wickets',
    description: 'Commonly confused words: wickers and wickets',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwickers\b/gi,
    message: 'Check: "wickers" ("wickers") vs "wickets" ("wickets"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wickets';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wicket_wicker_4300',
    name: 'wicket vs wicker',
    description: 'Commonly confused words: wicket and wicker',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwicket\b/gi,
    message: 'Check: "wicket" ("wicket") vs "wicker" ("wicker"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wicker';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_widely_wifely_4301',
    name: 'widely vs wifely',
    description: 'Commonly confused words: widely and wifely',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwidely\b/gi,
    message: 'Check: "widely" ("widely") vs "wifely" ("wifely"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wifely';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_widely_wisely_4302',
    name: 'widely vs wisely',
    description: 'Commonly confused words: widely and wisely',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwidely\b/gi,
    message: 'Check: "widely" ("widely") vs "wisely" ("wisely"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wisely';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_widest_wisest_4303',
    name: 'widest vs wisest',
    description: 'Commonly confused words: widest and wisest',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwidest\b/gi,
    message: 'Check: "widest" ("widest") vs "wisest" ("wisest"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wisest';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wife_wide_4304',
    name: 'wife vs wide',
    description: 'Commonly confused words: wife and wide',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwife\b/gi,
    message: 'Check: "wife" ("wife") vs "wide" ("wide"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wide';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wiggled_wiggles_4305',
    name: 'wiggled vs wiggles',
    description: 'Commonly confused words: wiggled and wiggles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwiggled\b/gi,
    message: 'Check: "wiggled" ("wiggled") vs "wiggles" ("wiggles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wiggles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wilted_silted_4306',
    name: 'wilted vs silted',
    description: 'Commonly confused words: wilted and silted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwilted\b/gi,
    message: 'Check: "wilted" ("wilted") vs "silted" ("silted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'silted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wilt_silt_4307',
    name: 'wilt vs silt',
    description: 'Commonly confused words: wilt and silt',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwilt\b/gi,
    message: 'Check: "wilt" ("wilt") vs "silt" ("silt"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'silt';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wilts_silts_4308',
    name: 'wilts vs silts',
    description: 'Commonly confused words: wilts and silts',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwilts\b/gi,
    message: 'Check: "wilts" ("wilts") vs "silts" ("silts"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'silts';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_winced_winded_4309',
    name: 'winced vs winded',
    description: 'Commonly confused words: winced and winded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwinced\b/gi,
    message: 'Check: "winced" ("winced") vs "winded" ("winded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'winded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_winched_winches_4310',
    name: 'winched vs winches',
    description: 'Commonly confused words: winched and winches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwinched\b/gi,
    message: 'Check: "winched" ("winched") vs "winches" ("winches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'winches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_winged_singed_4311',
    name: 'winged vs singed',
    description: 'Commonly confused words: winged and singed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwinged\b/gi,
    message: 'Check: "winged" ("winged") vs "singed" ("singed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'singed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_winning_sinning_4312',
    name: 'winning vs sinning',
    description: 'Commonly confused words: winning and sinning',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwinning\b/gi,
    message: 'Check: "winning" ("winning") vs "sinning" ("sinning"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sinning';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wins_sins_4313',
    name: 'wins vs sins',
    description: 'Commonly confused words: wins and sins',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwins\b/gi,
    message: 'Check: "wins" ("wins") vs "sins" ("sins"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sins';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wire_sire_4314',
    name: 'wire vs sire',
    description: 'Commonly confused words: wire and sire',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwire\b/gi,
    message: 'Check: "wire" ("wire") vs "sire" ("sire"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sire';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wise_wide_4315',
    name: 'wise vs wide',
    description: 'Commonly confused words: wise and wide',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwise\b/gi,
    message: 'Check: "wise" ("wise") vs "wide" ("wide"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wide';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wished_wishes_4316',
    name: 'wished vs wishes',
    description: 'Commonly confused words: wished and wishes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwished\b/gi,
    message: 'Check: "wished" ("wished") vs "wishes" ("wishes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wishes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_witched_witches_4317',
    name: 'witched vs witches',
    description: 'Commonly confused words: witched and witches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwitched\b/gi,
    message: 'Check: "witched" ("witched") vs "witches" ("witches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'witches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_witnessed_witnesses_4318',
    name: 'witnessed vs witnesses',
    description: 'Commonly confused words: witnessed and witnesses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwitnessed\b/gi,
    message: 'Check: "witnessed" ("witnessed") vs "witnesses" ("witnesses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'witnesses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_witters_sitters_4319',
    name: 'witters vs sitters',
    description: 'Commonly confused words: witters and sitters',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwitters\b/gi,
    message: 'Check: "witters" ("witters") vs "sitters" ("sitters"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sitters';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wolfs_wolds_4320',
    name: 'wolfs vs wolds',
    description: 'Commonly confused words: wolfs and wolds',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwolfs\b/gi,
    message: 'Check: "wolfs" ("wolfs") vs "wolds" ("wolds"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wolds';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wops_sops_4321',
    name: 'wops vs sops',
    description: 'Commonly confused words: wops and sops',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwops\b/gi,
    message: 'Check: "wops" ("wops") vs "sops" ("sops"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sops';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_worried_worries_4322',
    name: 'worried vs worries',
    description: 'Commonly confused words: worried and worries',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bworried\b/gi,
    message: 'Check: "worried" ("worried") vs "worries" ("worries"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'worries';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wounded_sounded_4323',
    name: 'wounded vs sounded',
    description: 'Commonly confused words: wounded and sounded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwounded\b/gi,
    message: 'Check: "wounded" ("wounded") vs "sounded" ("sounded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sounded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wounding_sounding_4324',
    name: 'wounding vs sounding',
    description: 'Commonly confused words: wounding and sounding',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwounding\b/gi,
    message: 'Check: "wounding" ("wounding") vs "sounding" ("sounding"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sounding';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wowing_sowing_4325',
    name: 'wowing vs sowing',
    description: 'Commonly confused words: wowing and sowing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwowing\b/gi,
    message: 'Check: "wowing" ("wowing") vs "sowing" ("sowing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'sowing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wretches_wretched_4326',
    name: 'wretches vs wretched',
    description: 'Commonly confused words: wretches and wretched',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwretches\b/gi,
    message: 'Check: "wretches" ("wretches") vs "wretched" ("wretched"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wretched';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wringing_wronging_4327',
    name: 'wringing vs wronging',
    description: 'Commonly confused words: wringing and wronging',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwringing\b/gi,
    message: 'Check: "wringing" ("wringing") vs "wronging" ("wronging"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wronging';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_wrinkled_wrinkles_4328',
    name: 'wrinkled vs wrinkles',
    description: 'Commonly confused words: wrinkled and wrinkles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bwrinkled\b/gi,
    message: 'Check: "wrinkled" ("wrinkled") vs "wrinkles" ("wrinkles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'wrinkles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
