/**
 * Auto-generated confusion rules (U)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.527Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesU: GrammarRule[] = [
  {
    id: 'confusion_us_use_789',
    name: 'us vs use',
    description: 'Commonly confused words: us and use',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bus\b/gi,
    message: 'Check: "us" ("us") vs "use" ("use"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'use';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_unbalanced_unbalances_4155',
    name: 'unbalanced vs unbalances',
    description: 'Commonly confused words: unbalanced and unbalances',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunbalanced\b/gi,
    message: 'Check: "unbalanced" ("unbalanced") vs "unbalances" ("unbalances"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unbalances';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_uncharged_uncharted_4156',
    name: 'uncharged vs uncharted',
    description: 'Commonly confused words: uncharged and uncharted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\buncharged\b/gi,
    message: 'Check: "uncharged" ("uncharged") vs "uncharted" ("uncharted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'uncharted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_uncoil_uncool_4157',
    name: 'uncoil vs uncool',
    description: 'Commonly confused words: uncoil and uncool',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\buncoil\b/gi,
    message: 'Check: "uncoil" ("uncoil") vs "uncool" ("uncool"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'uncool';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_uncoupled_uncouples_4158',
    name: 'uncoupled vs uncouples',
    description: 'Commonly confused words: uncoupled and uncouples',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\buncoupled\b/gi,
    message: 'Check: "uncoupled" ("uncoupled") vs "uncouples" ("uncouples"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'uncouples';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_undergone_undertone_4159',
    name: 'undergone vs undertone',
    description: 'Commonly confused words: undergone and undertone',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bundergone\b/gi,
    message: 'Check: "undergone" ("undergone") vs "undertone" ("undertone"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'undertone';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_undermined_undermines_4160',
    name: 'undermined vs undermines',
    description: 'Commonly confused words: undermined and undermines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bundermined\b/gi,
    message: 'Check: "undermined" ("undermined") vs "undermines" ("undermines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'undermines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_understated_understates_4161',
    name: 'understated vs understates',
    description: 'Commonly confused words: understated and understates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunderstated\b/gi,
    message: 'Check: "understated" ("understated") vs "understates" ("understates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'understates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_undervalued_undervalues_4162',
    name: 'undervalued vs undervalues',
    description: 'Commonly confused words: undervalued and undervalues',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bundervalued\b/gi,
    message: 'Check: "undervalued" ("undervalued") vs "undervalues" ("undervalues"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'undervalues';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_underwrite_underwrote_4163',
    name: 'underwrite vs underwrote',
    description: 'Commonly confused words: underwrite and underwrote',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunderwrite\b/gi,
    message: 'Check: "underwrite" ("underwrite") vs "underwrote" ("underwrote"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'underwrote';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_unheeded_unneeded_4164',
    name: 'unheeded vs unneeded',
    description: 'Commonly confused words: unheeded and unneeded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunheeded\b/gi,
    message: 'Check: "unheeded" ("unheeded") vs "unneeded" ("unneeded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unneeded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_unnerved_unnerves_4165',
    name: 'unnerved vs unnerves',
    description: 'Commonly confused words: unnerved and unnerves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunnerved\b/gi,
    message: 'Check: "unnerved" ("unnerved") vs "unnerves" ("unnerves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unnerves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_unreachable_unteachable_4166',
    name: 'unreachable vs unteachable',
    description: 'Commonly confused words: unreachable and unteachable',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunreachable\b/gi,
    message: 'Check: "unreachable" ("unreachable") vs "unteachable" ("unteachable"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unteachable';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_unsettled_unsettles_4167',
    name: 'unsettled vs unsettles',
    description: 'Commonly confused words: unsettled and unsettles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bunsettled\b/gi,
    message: 'Check: "unsettled" ("unsettled") vs "unsettles" ("unsettles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unsettles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_untangled_untangles_4168',
    name: 'untangled vs untangles',
    description: 'Commonly confused words: untangled and untangles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\buntangled\b/gi,
    message: 'Check: "untangled" ("untangled") vs "untangles" ("untangles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'untangles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_updated_updates_4169',
    name: 'updated vs updates',
    description: 'Commonly confused words: updated and updates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bupdated\b/gi,
    message: 'Check: "updated" ("updated") vs "updates" ("updates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'updates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_upgraded_upgrades_4170',
    name: 'upgraded vs upgrades',
    description: 'Commonly confused words: upgraded and upgrades',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bupgraded\b/gi,
    message: 'Check: "upgraded" ("upgraded") vs "upgrades" ("upgrades"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'upgrades';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_upstaged_upstages_4171',
    name: 'upstaged vs upstages',
    description: 'Commonly confused words: upstaged and upstages',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bupstaged\b/gi,
    message: 'Check: "upstaged" ("upstaged") vs "upstages" ("upstages"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'upstages';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_upstage_upstate_4172',
    name: 'upstage vs upstate',
    description: 'Commonly confused words: upstage and upstate',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bupstage\b/gi,
    message: 'Check: "upstage" ("upstage") vs "upstate" ("upstate"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'upstate';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_utilized_utilizes_4173',
    name: 'utilized vs utilizes',
    description: 'Commonly confused words: utilized and utilizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\butilized\b/gi,
    message: 'Check: "utilized" ("utilized") vs "utilizes" ("utilizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'utilizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
