/**
 * Auto-generated confusion rules (I)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.492Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesI: GrammarRule[] = [
  {
    id: 'confusion_illusion_allusion_27',
    name: 'illusion vs allusion',
    description: 'Commonly confused words: illusion and allusion',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\billusion\b/gi,
    message: 'Did you mean "allusion"? "illusion" ("illusion") is often confused with "allusion" ("allusion").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'allusion';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_illusions_allusions_29',
    name: 'illusions vs allusions',
    description: 'Commonly confused words: illusions and allusions',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\billusions\b/gi,
    message: 'Did you mean "allusions"? "illusions" ("illusions") is often confused with "allusions" ("allusions").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'allusions';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imply_infer_366',
    name: 'imply vs infer',
    description: 'Commonly confused words: imply and infer',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimply\b/gi,
    message: 'Check: "imply" ("imply") vs "infer" ("infer"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'infer';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_improved_improvised_367',
    name: 'improved vs improvised',
    description: 'Commonly confused words: improved and improvised',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimproved\b/gi,
    message: 'Check: "improved" ("improved") vs "improvised" ("improvised"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'improvised';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incites_insights_368',
    name: 'incites vs insights',
    description: 'Commonly confused words: incites and insights',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincites\b/gi,
    message: 'Check: "incites" ("incites") vs "insights" ("insights"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'insights';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inc_ink_369',
    name: 'inc vs ink',
    description: 'Commonly confused words: inc and ink',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binc\b/gi,
    message: 'Check: "inc" ("inc") vs "ink" ("ink"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ink';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_in_inn_370',
    name: 'in vs inn',
    description: 'Commonly confused words: in and inn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bin\b/gi,
    message: 'Check: "in" ("in") vs "inn" ("inn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inns_ins_371',
    name: 'inns vs ins',
    description: 'Commonly confused words: inns and ins',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binns\b/gi,
    message: 'Check: "inns" ("inns") vs "ins" ("ins"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ins';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_if_of_766',
    name: 'if vs of',
    description: 'Commonly confused words: if and of',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bif\b/gi,
    message: 'Did you mean "of"? "if" ("if") is often confused with "of" ("of").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'of';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ibid_ibis_2483',
    name: 'ibid vs ibis',
    description: 'Commonly confused words: ibid and ibis',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bibid\b/gi,
    message: 'Check: "ibid" ("ibid") vs "ibis" ("ibis"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ibis';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ibis_obis_2484',
    name: 'ibis vs obis',
    description: 'Commonly confused words: ibis and obis',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bibis\b/gi,
    message: 'Check: "ibis" ("ibis") vs "obis" ("obis"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obis';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_iced_ices_2485',
    name: 'iced vs ices',
    description: 'Commonly confused words: iced and ices',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\biced\b/gi,
    message: 'Check: "iced" ("iced") vs "ices" ("ices"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ices';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ices_ides_2486',
    name: 'ices vs ides',
    description: 'Commonly confused words: ices and ides',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bices\b/gi,
    message: 'Check: "ices" ("ices") vs "ides" ("ides"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ides';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_idealized_idealizes_2487',
    name: 'idealized vs idealizes',
    description: 'Commonly confused words: idealized and idealizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bidealized\b/gi,
    message: 'Check: "idealized" ("idealized") vs "idealizes" ("idealizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'idealizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_idled_idles_2488',
    name: 'idled vs idles',
    description: 'Commonly confused words: idled and idles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bidled\b/gi,
    message: 'Check: "idled" ("idled") vs "idles" ("idles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'idles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_idle_isle_2489',
    name: 'idle vs isle',
    description: 'Commonly confused words: idle and isle',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bidle\b/gi,
    message: 'Check: "idle" ("idle") vs "isle" ("isle"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'isle';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ifs_ids_2490',
    name: 'ifs vs ids',
    description: 'Commonly confused words: ifs and ids',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bifs\b/gi,
    message: 'Check: "ifs" ("ifs") vs "ids" ("ids"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ids';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_illumined_illumines_2491',
    name: 'illumined vs illumines',
    description: 'Commonly confused words: illumined and illumines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\billumined\b/gi,
    message: 'Check: "illumined" ("illumined") vs "illumines" ("illumines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'illumines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imbalanced_imbalances_2492',
    name: 'imbalanced vs imbalances',
    description: 'Commonly confused words: imbalanced and imbalances',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimbalanced\b/gi,
    message: 'Check: "imbalanced" ("imbalanced") vs "imbalances" ("imbalances"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'imbalances';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imbibed_imbibes_2493',
    name: 'imbibed vs imbibes',
    description: 'Commonly confused words: imbibed and imbibes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimbibed\b/gi,
    message: 'Check: "imbibed" ("imbibed") vs "imbibes" ("imbibes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'imbibes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imbued_imbues_2494',
    name: 'imbued vs imbues',
    description: 'Commonly confused words: imbued and imbues',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimbued\b/gi,
    message: 'Check: "imbued" ("imbued") vs "imbues" ("imbues"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'imbues';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_immobilized_immobilizes_2495',
    name: 'immobilized vs immobilizes',
    description: 'Commonly confused words: immobilized and immobilizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimmobilized\b/gi,
    message: 'Check: "immobilized" ("immobilized") vs "immobilizes" ("immobilizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'immobilizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_immortalized_immortalizes_2496',
    name: 'immortalized vs immortalizes',
    description: 'Commonly confused words: immortalized and immortalizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimmortalized\b/gi,
    message: 'Check: "immortalized" ("immortalized") vs "immortalizes" ("immortalizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'immortalizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_immunized_immunizes_2497',
    name: 'immunized vs immunizes',
    description: 'Commonly confused words: immunized and immunizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimmunized\b/gi,
    message: 'Check: "immunized" ("immunized") vs "immunizes" ("immunizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'immunizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impatient_inpatient_2498',
    name: 'impatient vs inpatient',
    description: 'Commonly confused words: impatient and inpatient',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpatient\b/gi,
    message: 'Check: "impatient" ("impatient") vs "inpatient" ("inpatient"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inpatient';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impeached_impeaches_2499',
    name: 'impeached vs impeaches',
    description: 'Commonly confused words: impeached and impeaches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpeached\b/gi,
    message: 'Check: "impeached" ("impeached") vs "impeaches" ("impeaches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'impeaches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_implicated_implicates_2500',
    name: 'implicated vs implicates',
    description: 'Commonly confused words: implicated and implicates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimplicated\b/gi,
    message: 'Check: "implicated" ("implicated") vs "implicates" ("implicates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'implicates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_implied_implies_2501',
    name: 'implied vs implies',
    description: 'Commonly confused words: implied and implies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimplied\b/gi,
    message: 'Check: "implied" ("implied") vs "implies" ("implies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'implies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imploded_implodes_2502',
    name: 'imploded vs implodes',
    description: 'Commonly confused words: imploded and implodes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimploded\b/gi,
    message: 'Check: "imploded" ("imploded") vs "implodes" ("implodes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'implodes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impoverished_impoverishes_2503',
    name: 'impoverished vs impoverishes',
    description: 'Commonly confused words: impoverished and impoverishes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpoverished\b/gi,
    message: 'Check: "impoverished" ("impoverished") vs "impoverishes" ("impoverishes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'impoverishes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impregnated_impregnates_2504',
    name: 'impregnated vs impregnates',
    description: 'Commonly confused words: impregnated and impregnates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpregnated\b/gi,
    message: 'Check: "impregnated" ("impregnated") vs "impregnates" ("impregnates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'impregnates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impulsed_impulses_2505',
    name: 'impulsed vs impulses',
    description: 'Commonly confused words: impulsed and impulses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpulsed\b/gi,
    message: 'Check: "impulsed" ("impulsed") vs "impulses" ("impulses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'impulses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_impure_impute_2506',
    name: 'impure vs impute',
    description: 'Commonly confused words: impure and impute',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimpure\b/gi,
    message: 'Check: "impure" ("impure") vs "impute" ("impute"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'impute';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_imputed_imputes_2507',
    name: 'imputed vs imputes',
    description: 'Commonly confused words: imputed and imputes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bimputed\b/gi,
    message: 'Check: "imputed" ("imputed") vs "imputes" ("imputes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'imputes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inactivated_inactivates_2508',
    name: 'inactivated vs inactivates',
    description: 'Commonly confused words: inactivated and inactivates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binactivated\b/gi,
    message: 'Check: "inactivated" ("inactivated") vs "inactivates" ("inactivates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inactivates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inborn_unborn_2509',
    name: 'inborn vs unborn',
    description: 'Commonly confused words: inborn and unborn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binborn\b/gi,
    message: 'Check: "inborn" ("inborn") vs "unborn" ("unborn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unborn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incarcerated_incarcerates_2510',
    name: 'incarcerated vs incarcerates',
    description: 'Commonly confused words: incarcerated and incarcerates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincarcerated\b/gi,
    message: 'Check: "incarcerated" ("incarcerated") vs "incarcerates" ("incarcerates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'incarcerates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incensed_incenses_2511',
    name: 'incensed vs incenses',
    description: 'Commonly confused words: incensed and incenses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincensed\b/gi,
    message: 'Check: "incensed" ("incensed") vs "incenses" ("incenses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'incenses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incest_invest_2512',
    name: 'incest vs invest',
    description: 'Commonly confused words: incest and invest',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincest\b/gi,
    message: 'Check: "incest" ("incest") vs "invest" ("invest"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invest';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inciting_inditing_2513',
    name: 'inciting vs inditing',
    description: 'Commonly confused words: inciting and inditing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binciting\b/gi,
    message: 'Check: "inciting" ("inciting") vs "inditing" ("inditing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inditing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_included_includes_2514',
    name: 'included vs includes',
    description: 'Commonly confused words: included and includes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincluded\b/gi,
    message: 'Check: "included" ("included") vs "includes" ("includes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'includes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inconveniences_inconvenienced_2515',
    name: 'inconveniences vs inconvenienced',
    description: 'Commonly confused words: inconveniences and inconvenienced',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binconveniences\b/gi,
    message: 'Check: "inconveniences" ("inconveniences") vs "inconvenienced" ("inconvenienced"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inconvenienced';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incorporated_incorporates_2516',
    name: 'incorporated vs incorporates',
    description: 'Commonly confused words: incorporated and incorporates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincorporated\b/gi,
    message: 'Check: "incorporated" ("incorporated") vs "incorporates" ("incorporates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'incorporates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incriminated_incriminates_2517',
    name: 'incriminated vs incriminates',
    description: 'Commonly confused words: incriminated and incriminates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincriminated\b/gi,
    message: 'Check: "incriminated" ("incriminated") vs "incriminates" ("incriminates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'incriminates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_incubated_incubates_2518',
    name: 'incubated vs incubates',
    description: 'Commonly confused words: incubated and incubates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bincubated\b/gi,
    message: 'Check: "incubated" ("incubated") vs "incubates" ("incubates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'incubates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inculcated_inculcates_2519',
    name: 'inculcated vs inculcates',
    description: 'Commonly confused words: inculcated and inculcates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binculcated\b/gi,
    message: 'Check: "inculcated" ("inculcated") vs "inculcates" ("inculcates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inculcates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indented_indebted_2520',
    name: 'indented vs indebted',
    description: 'Commonly confused words: indented and indebted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindented\b/gi,
    message: 'Check: "indented" ("indented") vs "indebted" ("indebted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indebted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indentures_indentured_2521',
    name: 'indentures vs indentured',
    description: 'Commonly confused words: indentures and indentured',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindentures\b/gi,
    message: 'Check: "indentures" ("indentures") vs "indentured" ("indentured"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indentured';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indexed_indexes_2522',
    name: 'indexed vs indexes',
    description: 'Commonly confused words: indexed and indexes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindexed\b/gi,
    message: 'Check: "indexed" ("indexed") vs "indexes" ("indexes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indexes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indicated_indicates_2523',
    name: 'indicated vs indicates',
    description: 'Commonly confused words: indicated and indicates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindicated\b/gi,
    message: 'Check: "indicated" ("indicated") vs "indicates" ("indicates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indicates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indices_induces_2524',
    name: 'indices vs induces',
    description: 'Commonly confused words: indices and induces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindices\b/gi,
    message: 'Check: "indices" ("indices") vs "induces" ("induces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'induces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indicted_inducted_2525',
    name: 'indicted vs inducted',
    description: 'Commonly confused words: indicted and inducted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindicted\b/gi,
    message: 'Check: "indicted" ("indicted") vs "inducted" ("inducted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inducted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indoctrinated_indoctrinates_2526',
    name: 'indoctrinated vs indoctrinates',
    description: 'Commonly confused words: indoctrinated and indoctrinates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindoctrinated\b/gi,
    message: 'Check: "indoctrinated" ("indoctrinated") vs "indoctrinates" ("indoctrinates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indoctrinates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_induced_induces_2527',
    name: 'induced vs induces',
    description: 'Commonly confused words: induced and induces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binduced\b/gi,
    message: 'Check: "induced" ("induced") vs "induces" ("induces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'induces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_indulged_indulges_2528',
    name: 'indulged vs indulges',
    description: 'Commonly confused words: indulged and indulges',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bindulged\b/gi,
    message: 'Check: "indulged" ("indulged") vs "indulges" ("indulges"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'indulges';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inebriated_inebriates_2529',
    name: 'inebriated vs inebriates',
    description: 'Commonly confused words: inebriated and inebriates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binebriated\b/gi,
    message: 'Check: "inebriated" ("inebriated") vs "inebriates" ("inebriates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inebriates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infested_ingested_2530',
    name: 'infested vs ingested',
    description: 'Commonly confused words: infested and ingested',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfested\b/gi,
    message: 'Check: "infested" ("infested") vs "ingested" ("ingested"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ingested';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infested_invested_2531',
    name: 'infested vs invested',
    description: 'Commonly confused words: infested and invested',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfested\b/gi,
    message: 'Check: "infested" ("infested") vs "invested" ("invested"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invested';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infesting_ingesting_2532',
    name: 'infesting vs ingesting',
    description: 'Commonly confused words: infesting and ingesting',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfesting\b/gi,
    message: 'Check: "infesting" ("infesting") vs "ingesting" ("ingesting"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ingesting';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infesting_investing_2533',
    name: 'infesting vs investing',
    description: 'Commonly confused words: infesting and investing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfesting\b/gi,
    message: 'Check: "infesting" ("infesting") vs "investing" ("investing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'investing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infilled_unfilled_2534',
    name: 'infilled vs unfilled',
    description: 'Commonly confused words: infilled and unfilled',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfilled\b/gi,
    message: 'Check: "infilled" ("infilled") vs "unfilled" ("unfilled"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unfilled';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inflamed_inflames_2535',
    name: 'inflamed vs inflames',
    description: 'Commonly confused words: inflamed and inflames',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binflamed\b/gi,
    message: 'Check: "inflamed" ("inflamed") vs "inflames" ("inflames"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inflames';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inflated_inflates_2536',
    name: 'inflated vs inflates',
    description: 'Commonly confused words: inflated and inflates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binflated\b/gi,
    message: 'Check: "inflated" ("inflated") vs "inflates" ("inflates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inflates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_influenced_influences_2537',
    name: 'influenced vs influences',
    description: 'Commonly confused words: influenced and influences',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfluenced\b/gi,
    message: 'Check: "influenced" ("influenced") vs "influences" ("influences"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'influences';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inform_infirm_2538',
    name: 'inform vs infirm',
    description: 'Commonly confused words: inform and infirm',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binform\b/gi,
    message: 'Check: "inform" ("inform") vs "infirm" ("infirm"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'infirm';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infringed_infringes_2539',
    name: 'infringed vs infringes',
    description: 'Commonly confused words: infringed and infringes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfringed\b/gi,
    message: 'Check: "infringed" ("infringed") vs "infringes" ("infringes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'infringes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infuriated_infuriates_2540',
    name: 'infuriated vs infuriates',
    description: 'Commonly confused words: infuriated and infuriates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfuriated\b/gi,
    message: 'Check: "infuriated" ("infuriated") vs "infuriates" ("infuriates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'infuriates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_infused_infuses_2541',
    name: 'infused vs infuses',
    description: 'Commonly confused words: infused and infuses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binfused\b/gi,
    message: 'Check: "infused" ("infused") vs "infuses" ("infuses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'infuses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inhaled_inhales_2542',
    name: 'inhaled vs inhales',
    description: 'Commonly confused words: inhaled and inhales',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binhaled\b/gi,
    message: 'Check: "inhaled" ("inhaled") vs "inhales" ("inhales"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inhales';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_initialized_initializes_2543',
    name: 'initialized vs initializes',
    description: 'Commonly confused words: initialized and initializes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binitialized\b/gi,
    message: 'Check: "initialized" ("initialized") vs "initializes" ("initializes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'initializes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inmate_innate_2544',
    name: 'inmate vs innate',
    description: 'Commonly confused words: inmate and innate',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binmate\b/gi,
    message: 'Check: "inmate" ("inmate") vs "innate" ("innate"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'innate';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_innervated_innervates_2545',
    name: 'innervated vs innervates',
    description: 'Commonly confused words: innervated and innervates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binnervated\b/gi,
    message: 'Check: "innervated" ("innervated") vs "innervates" ("innervates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'innervates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inrush_onrush_2546',
    name: 'inrush vs onrush',
    description: 'Commonly confused words: inrush and onrush',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binrush\b/gi,
    message: 'Check: "inrush" ("inrush") vs "onrush" ("onrush"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'onrush';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inscribed_inscribes_2547',
    name: 'inscribed vs inscribes',
    description: 'Commonly confused words: inscribed and inscribes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binscribed\b/gi,
    message: 'Check: "inscribed" ("inscribed") vs "inscribes" ("inscribes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inscribes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inseminated_inseminates_2548',
    name: 'inseminated vs inseminates',
    description: 'Commonly confused words: inseminated and inseminates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binseminated\b/gi,
    message: 'Check: "inseminated" ("inseminated") vs "inseminates" ("inseminates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inseminates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inset_unset_2549',
    name: 'inset vs unset',
    description: 'Commonly confused words: inset and unset',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binset\b/gi,
    message: 'Check: "inset" ("inset") vs "unset" ("unset"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unset';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_insinuated_insinuates_2550',
    name: 'insinuated vs insinuates',
    description: 'Commonly confused words: insinuated and insinuates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binsinuated\b/gi,
    message: 'Check: "insinuated" ("insinuated") vs "insinuates" ("insinuates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'insinuates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_instantiated_instantiates_2551',
    name: 'instantiated vs instantiates',
    description: 'Commonly confused words: instantiated and instantiates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstantiated\b/gi,
    message: 'Check: "instantiated" ("instantiated") vs "instantiates" ("instantiates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'instantiates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_instated_instates_2552',
    name: 'instated vs instates',
    description: 'Commonly confused words: instated and instates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstated\b/gi,
    message: 'Check: "instated" ("instated") vs "instates" ("instates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'instates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_instated_unstated_2553',
    name: 'instated vs unstated',
    description: 'Commonly confused words: instated and unstated',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstated\b/gi,
    message: 'Check: "instated" ("instated") vs "unstated" ("unstated"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unstated';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_instigated_instigates_2554',
    name: 'instigated vs instigates',
    description: 'Commonly confused words: instigated and instigates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstigated\b/gi,
    message: 'Check: "instigated" ("instigated") vs "instigates" ("instigates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'instigates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_instituted_institutes_2555',
    name: 'instituted vs institutes',
    description: 'Commonly confused words: instituted and institutes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstituted\b/gi,
    message: 'Check: "instituted" ("instituted") vs "institutes" ("institutes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'institutes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_institutionalized_institutionalizes_2556',
    name: 'institutionalized vs institutionalizes',
    description: 'Commonly confused words: institutionalized and institutionalizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binstitutionalized\b/gi,
    message: 'Check: "institutionalized" ("institutionalized") vs "institutionalizes" ("institutionalizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'institutionalizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_insulated_insulates_2557',
    name: 'insulated vs insulates',
    description: 'Commonly confused words: insulated and insulates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binsulated\b/gi,
    message: 'Check: "insulated" ("insulated") vs "insulates" ("insulates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'insulates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_insured_insures_2558',
    name: 'insured vs insures',
    description: 'Commonly confused words: insured and insures',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binsured\b/gi,
    message: 'Check: "insured" ("insured") vs "insures" ("insures"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'insures';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_insure_unsure_2559',
    name: 'insure vs unsure',
    description: 'Commonly confused words: insure and unsure',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binsure\b/gi,
    message: 'Check: "insure" ("insure") vs "unsure" ("unsure"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'unsure';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intended_untended_2560',
    name: 'intended vs untended',
    description: 'Commonly confused words: intended and untended',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintended\b/gi,
    message: 'Check: "intended" ("intended") vs "untended" ("untended"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'untended';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interfered_interferes_2561',
    name: 'interfered vs interferes',
    description: 'Commonly confused words: interfered and interferes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterfered\b/gi,
    message: 'Check: "interfered" ("interfered") vs "interferes" ("interferes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'interferes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interlaced_interlaces_2562',
    name: 'interlaced vs interlaces',
    description: 'Commonly confused words: interlaced and interlaces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterlaced\b/gi,
    message: 'Check: "interlaced" ("interlaced") vs "interlaces" ("interlaces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'interlaces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interleaved_interleaves_2563',
    name: 'interleaved vs interleaves',
    description: 'Commonly confused words: interleaved and interleaves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterleaved\b/gi,
    message: 'Check: "interleaved" ("interleaved") vs "interleaves" ("interleaves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'interleaves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intermingled_intermingles_2564',
    name: 'intermingled vs intermingles',
    description: 'Commonly confused words: intermingled and intermingles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintermingled\b/gi,
    message: 'Check: "intermingled" ("intermingled") vs "intermingles" ("intermingles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intermingles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intermixed_intermixes_2565',
    name: 'intermixed vs intermixes',
    description: 'Commonly confused words: intermixed and intermixes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintermixed\b/gi,
    message: 'Check: "intermixed" ("intermixed") vs "intermixes" ("intermixes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intermixes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interned_internee_2566',
    name: 'interned vs internee',
    description: 'Commonly confused words: interned and internee',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterned\b/gi,
    message: 'Check: "interned" ("interned") vs "internee" ("internee"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'internee';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interposed_interposes_2567',
    name: 'interposed vs interposes',
    description: 'Commonly confused words: interposed and interposes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterposed\b/gi,
    message: 'Check: "interposed" ("interposed") vs "interposes" ("interposes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'interposes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interrelated_interrelates_2568',
    name: 'interrelated vs interrelates',
    description: 'Commonly confused words: interrelated and interrelates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterrelated\b/gi,
    message: 'Check: "interrelated" ("interrelated") vs "interrelates" ("interrelates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'interrelates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_interspersed_intersperses_2569',
    name: 'interspersed vs intersperses',
    description: 'Commonly confused words: interspersed and intersperses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binterspersed\b/gi,
    message: 'Check: "interspersed" ("interspersed") vs "intersperses" ("intersperses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intersperses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intertwined_intertwines_2570',
    name: 'intertwined vs intertwines',
    description: 'Commonly confused words: intertwined and intertwines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintertwined\b/gi,
    message: 'Check: "intertwined" ("intertwined") vs "intertwines" ("intertwines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intertwines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intimated_intimates_2571',
    name: 'intimated vs intimates',
    description: 'Commonly confused words: intimated and intimates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintimated\b/gi,
    message: 'Check: "intimated" ("intimated") vs "intimates" ("intimates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intimates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intimidated_intimidates_2572',
    name: 'intimidated vs intimidates',
    description: 'Commonly confused words: intimidated and intimidates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintimidated\b/gi,
    message: 'Check: "intimidated" ("intimidated") vs "intimidates" ("intimidates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intimidates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intoxicated_intoxicates_2573',
    name: 'intoxicated vs intoxicates',
    description: 'Commonly confused words: intoxicated and intoxicates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintoxicated\b/gi,
    message: 'Check: "intoxicated" ("intoxicated") vs "intoxicates" ("intoxicates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intoxicates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intrigued_intrigues_2574',
    name: 'intrigued vs intrigues',
    description: 'Commonly confused words: intrigued and intrigues',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintrigued\b/gi,
    message: 'Check: "intrigued" ("intrigued") vs "intrigues" ("intrigues"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intrigues';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_intruded_intrudes_2575',
    name: 'intruded vs intrudes',
    description: 'Commonly confused words: intruded and intrudes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bintruded\b/gi,
    message: 'Check: "intruded" ("intruded") vs "intrudes" ("intrudes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'intrudes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inundated_inundates_2576',
    name: 'inundated vs inundates',
    description: 'Commonly confused words: inundated and inundates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binundated\b/gi,
    message: 'Check: "inundated" ("inundated") vs "inundates" ("inundates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inundates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_invalidated_invalidates_2577',
    name: 'invalidated vs invalidates',
    description: 'Commonly confused words: invalidated and invalidates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binvalidated\b/gi,
    message: 'Check: "invalidated" ("invalidated") vs "invalidates" ("invalidates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invalidates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inventoried_inventories_2578',
    name: 'inventoried vs inventories',
    description: 'Commonly confused words: inventoried and inventories',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binventoried\b/gi,
    message: 'Check: "inventoried" ("inventoried") vs "inventories" ("inventories"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'inventories';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_invigorated_invigorates_2579',
    name: 'invigorated vs invigorates',
    description: 'Commonly confused words: invigorated and invigorates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binvigorated\b/gi,
    message: 'Check: "invigorated" ("invigorated") vs "invigorates" ("invigorates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invigorates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_invoiced_invoices_2580',
    name: 'invoiced vs invoices',
    description: 'Commonly confused words: invoiced and invoices',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binvoiced\b/gi,
    message: 'Check: "invoiced" ("invoiced") vs "invoices" ("invoices"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invoices';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_invoked_invokes_2581',
    name: 'invoked vs invokes',
    description: 'Commonly confused words: invoked and invokes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binvoked\b/gi,
    message: 'Check: "invoked" ("invoked") vs "invokes" ("invokes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'invokes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_involved_involves_2582',
    name: 'involved vs involves',
    description: 'Commonly confused words: involved and involves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binvolved\b/gi,
    message: 'Check: "involved" ("involved") vs "involves" ("involves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'involves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_inward_onward_2583',
    name: 'inward vs onward',
    description: 'Commonly confused words: inward and onward',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\binward\b/gi,
    message: 'Check: "inward" ("inward") vs "onward" ("onward"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'onward';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ionized_ionizes_2584',
    name: 'ionized vs ionizes',
    description: 'Commonly confused words: ionized and ionizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bionized\b/gi,
    message: 'Check: "ionized" ("ionized") vs "ionizes" ("ionizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ionizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irate_orate_2585',
    name: 'irate vs orate',
    description: 'Commonly confused words: irate and orate',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birate\b/gi,
    message: 'Check: "irate" ("irate") vs "orate" ("orate"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'orate';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irks_iris_2586',
    name: 'irks vs iris',
    description: 'Commonly confused words: irks and iris',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birks\b/gi,
    message: 'Check: "irks" ("irks") vs "iris" ("iris"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'iris';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irradiated_irradiates_2587',
    name: 'irradiated vs irradiates',
    description: 'Commonly confused words: irradiated and irradiates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birradiated\b/gi,
    message: 'Check: "irradiated" ("irradiated") vs "irradiates" ("irradiates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irradiates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigable_irritable_2588',
    name: 'irrigable vs irritable',
    description: 'Commonly confused words: irrigable and irritable',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigable\b/gi,
    message: 'Check: "irrigable" ("irrigable") vs "irritable" ("irritable"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritable';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigated_irrigates_2589',
    name: 'irrigated vs irrigates',
    description: 'Commonly confused words: irrigated and irrigates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigated\b/gi,
    message: 'Check: "irrigated" ("irrigated") vs "irrigates" ("irrigates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irrigates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigated_irritated_2590',
    name: 'irrigated vs irritated',
    description: 'Commonly confused words: irrigated and irritated',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigated\b/gi,
    message: 'Check: "irrigated" ("irrigated") vs "irritated" ("irritated"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritated';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigate_irritate_2591',
    name: 'irrigate vs irritate',
    description: 'Commonly confused words: irrigate and irritate',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigate\b/gi,
    message: 'Check: "irrigate" ("irrigate") vs "irritate" ("irritate"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritate';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigates_irritates_2592',
    name: 'irrigates vs irritates',
    description: 'Commonly confused words: irrigates and irritates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigates\b/gi,
    message: 'Check: "irrigates" ("irrigates") vs "irritates" ("irritates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigating_irritating_2593',
    name: 'irrigating vs irritating',
    description: 'Commonly confused words: irrigating and irritating',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigating\b/gi,
    message: 'Check: "irrigating" ("irrigating") vs "irritating" ("irritating"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritating';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_irrigation_irritation_2594',
    name: 'irrigation vs irritation',
    description: 'Commonly confused words: irrigation and irritation',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\birrigation\b/gi,
    message: 'Check: "irrigation" ("irrigation") vs "irritation" ("irritation"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'irritation';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_issued_issues_2595',
    name: 'issued vs issues',
    description: 'Commonly confused words: issued and issues',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bissued\b/gi,
    message: 'Check: "issued" ("issued") vs "issues" ("issues"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'issues';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_italicized_italicizes_2596',
    name: 'italicized vs italicizes',
    description: 'Commonly confused words: italicized and italicizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bitalicized\b/gi,
    message: 'Check: "italicized" ("italicized") vs "italicizes" ("italicizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'italicizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_itemized_itemizes_2597',
    name: 'itemized vs itemizes',
    description: 'Commonly confused words: itemized and itemizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bitemized\b/gi,
    message: 'Check: "itemized" ("itemized") vs "itemizes" ("itemizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'itemizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_iterated_iterates_2598',
    name: 'iterated vs iterates',
    description: 'Commonly confused words: iterated and iterates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\biterated\b/gi,
    message: 'Check: "iterated" ("iterated") vs "iterates" ("iterates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'iterates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
