/**
 * Auto-generated confusion rules (N)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.512Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesN: GrammarRule[] = [
  {
    id: 'confusion_nose_knows_382',
    name: 'nose vs knows',
    description: 'Commonly confused words: nose and knows',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnose\b/gi,
    message: 'Did you mean "knows"? "nose" ("nose") is often confused with "knows" ("knows").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knows';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_no_know_384',
    name: 'no vs know',
    description: 'Commonly confused words: no and know',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bno\b/gi,
    message: 'Did you mean "know"? "no" (negative) is often confused with "know" (to understand).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'know';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_now_know_387',
    name: 'now vs know',
    description: 'Commonly confused words: now and know',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnow\b/gi,
    message: 'Did you mean "know"? "now" ("now") is often confused with "know" (to understand).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'know';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nays_neighs_462',
    name: 'nays vs neighs',
    description: 'Commonly confused words: nays and neighs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnays\b/gi,
    message: 'Check: "nays" ("nays") vs "neighs" ("neighs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'neighs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_near_neat_463',
    name: 'near vs neat',
    description: 'Commonly confused words: near and neat',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnear\b/gi,
    message: 'Check: "near" ("near") vs "neat" ("neat"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'neat';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_new_news_464',
    name: 'new vs news',
    description: 'Commonly confused words: new and news',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnew\b/gi,
    message: 'Check: "new" (not old) vs "news" ("news"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'news';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nit_not_465',
    name: 'nit vs not',
    description: 'Commonly confused words: nit and not',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnit\b/gi,
    message: 'Check: "nit" ("nit") vs "not" ("not"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'not';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_no_now_466',
    name: 'no vs now',
    description: 'Commonly confused words: no and now',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bno\b/gi,
    message: 'Did you mean "now"? "no" (negative) is often confused with "now" ("now").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'now';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_now_no_467',
    name: 'now vs no',
    description: 'Commonly confused words: now and no',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnow\b/gi,
    message: 'Did you mean "no"? "now" ("now") is often confused with "no" (negative).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'no';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_none_nun_468',
    name: 'none vs nun',
    description: 'Commonly confused words: none and nun',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnone\b/gi,
    message: 'Check: "none" ("none") vs "nun" ("nun"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nun';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_no_on_470',
    name: 'no vs on',
    description: 'Commonly confused words: no and on',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bno\b/gi,
    message: 'Did you mean "on"? "no" (negative) is often confused with "on" ("on").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'on';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_not_note_471',
    name: 'not vs note',
    description: 'Commonly confused words: not and note',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnot\b/gi,
    message: 'Check: "not" ("not") vs "note" ("note"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'note';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_not_nut_472',
    name: 'not vs nut',
    description: 'Commonly confused words: not and nut',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnot\b/gi,
    message: 'Check: "not" ("not") vs "nut" ("nut"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nut';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nagged_bagged_2897',
    name: 'nagged vs bagged',
    description: 'Commonly confused words: nagged and bagged',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnagged\b/gi,
    message: 'Check: "nagged" ("nagged") vs "bagged" ("bagged"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bagged';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nagging_bagging_2898',
    name: 'nagging vs bagging',
    description: 'Commonly confused words: nagging and bagging',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnagging\b/gi,
    message: 'Check: "nagging" ("nagging") vs "bagging" ("bagging"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bagging';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nail_bail_2899',
    name: 'nail vs bail',
    description: 'Commonly confused words: nail and bail',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnail\b/gi,
    message: 'Check: "nail" ("nail") vs "bail" ("bail"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bail';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nailed_bailed_2900',
    name: 'nailed vs bailed',
    description: 'Commonly confused words: nailed and bailed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnailed\b/gi,
    message: 'Check: "nailed" ("nailed") vs "bailed" ("bailed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bailed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nail_hail_2901',
    name: 'nail vs hail',
    description: 'Commonly confused words: nail and hail',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnail\b/gi,
    message: 'Check: "nail" ("nail") vs "hail" ("hail"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hail';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nailing_bailing_2902',
    name: 'nailing vs bailing',
    description: 'Commonly confused words: nailing and bailing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnailing\b/gi,
    message: 'Check: "nailing" ("nailing") vs "bailing" ("bailing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bailing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nailing_mailing_2903',
    name: 'nailing vs mailing',
    description: 'Commonly confused words: nailing and mailing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnailing\b/gi,
    message: 'Check: "nailing" ("nailing") vs "mailing" ("mailing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'mailing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nails_mails_2904',
    name: 'nails vs mails',
    description: 'Commonly confused words: nails and mails',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnails\b/gi,
    message: 'Check: "nails" ("nails") vs "mails" ("mails"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'mails';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_naked_baked_2905',
    name: 'naked vs baked',
    description: 'Commonly confused words: naked and baked',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnaked\b/gi,
    message: 'Check: "naked" ("naked") vs "baked" ("baked"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'baked';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_named_names_2906',
    name: 'named vs names',
    description: 'Commonly confused words: named and names',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnamed\b/gi,
    message: 'Check: "named" ("named") vs "names" ("names"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'names';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_naps_baps_2907',
    name: 'naps vs baps',
    description: 'Commonly confused words: naps and baps',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnaps\b/gi,
    message: 'Check: "naps" ("naps") vs "baps" ("baps"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'baps';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_narrated_narrates_2908',
    name: 'narrated vs narrates',
    description: 'Commonly confused words: narrated and narrates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnarrated\b/gi,
    message: 'Check: "narrated" ("narrated") vs "narrates" ("narrates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'narrates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_narrow_barrow_2909',
    name: 'narrow vs barrow',
    description: 'Commonly confused words: narrow and barrow',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnarrow\b/gi,
    message: 'Check: "narrow" ("narrow") vs "barrow" ("barrow"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'barrow';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_narrow_marrow_2910',
    name: 'narrow vs marrow',
    description: 'Commonly confused words: narrow and marrow',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnarrow\b/gi,
    message: 'Check: "narrow" ("narrow") vs "marrow" ("marrow"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'marrow';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nationalized_nationalizes_2911',
    name: 'nationalized vs nationalizes',
    description: 'Commonly confused words: nationalized and nationalizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnationalized\b/gi,
    message: 'Check: "nationalized" ("nationalized") vs "nationalizes" ("nationalizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nationalizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_natter_batter_2912',
    name: 'natter vs batter',
    description: 'Commonly confused words: natter and batter',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnatter\b/gi,
    message: 'Check: "natter" ("natter") vs "batter" ("batter"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'batter';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_natters_batters_2913',
    name: 'natters vs batters',
    description: 'Commonly confused words: natters and batters',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnatters\b/gi,
    message: 'Check: "natters" ("natters") vs "batters" ("batters"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'batters';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_naturalized_naturalizes_2914',
    name: 'naturalized vs naturalizes',
    description: 'Commonly confused words: naturalized and naturalizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnaturalized\b/gi,
    message: 'Check: "naturalized" ("naturalized") vs "naturalizes" ("naturalizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'naturalizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nave_have_2915',
    name: 'nave vs have',
    description: 'Commonly confused words: nave and have',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnave\b/gi,
    message: 'Check: "nave" ("nave") vs "have" ("have"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'have';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nays_bays_2916',
    name: 'nays vs bays',
    description: 'Commonly confused words: nays and bays',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnays\b/gi,
    message: 'Check: "nays" ("nays") vs "bays" ("bays"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bays';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neap_heap_2917',
    name: 'neap vs heap',
    description: 'Commonly confused words: neap and heap',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneap\b/gi,
    message: 'Check: "neap" ("neap") vs "heap" ("heap"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'heap';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_near_bear_2918',
    name: 'near vs bear',
    description: 'Commonly confused words: near and bear',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnear\b/gi,
    message: 'Check: "near" ("near") vs "bear" (animal or to carry). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bear';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nearer_bearer_2919',
    name: 'nearer vs bearer',
    description: 'Commonly confused words: nearer and bearer',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnearer\b/gi,
    message: 'Check: "nearer" ("nearer") vs "bearer" ("bearer"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bearer';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nearer_hearer_2920',
    name: 'nearer vs hearer',
    description: 'Commonly confused words: nearer and hearer',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnearer\b/gi,
    message: 'Check: "nearer" ("nearer") vs "hearer" ("hearer"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hearer';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_near_hear_2921',
    name: 'near vs hear',
    description: 'Commonly confused words: near and hear',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnear\b/gi,
    message: 'Check: "near" ("near") vs "hear" (to perceive sound). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hear';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nearness_neatness_2922',
    name: 'nearness vs neatness',
    description: 'Commonly confused words: nearness and neatness',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnearness\b/gi,
    message: 'Check: "nearness" ("nearness") vs "neatness" ("neatness"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'neatness';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neater_beater_2923',
    name: 'neater vs beater',
    description: 'Commonly confused words: neater and beater',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneater\b/gi,
    message: 'Check: "neater" ("neater") vs "beater" ("beater"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'beater';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neater_heater_2924',
    name: 'neater vs heater',
    description: 'Commonly confused words: neater and heater',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneater\b/gi,
    message: 'Check: "neater" ("neater") vs "heater" ("heater"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'heater';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nebulae_nebular_2925',
    name: 'nebulae vs nebular',
    description: 'Commonly confused words: nebulae and nebular',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnebulae\b/gi,
    message: 'Check: "nebulae" ("nebulae") vs "nebular" ("nebular"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nebular';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neck_heck_2926',
    name: 'neck vs heck',
    description: 'Commonly confused words: neck and heck',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneck\b/gi,
    message: 'Check: "neck" ("neck") vs "heck" ("heck"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'heck';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_necklaced_necklaces_2927',
    name: 'necklaced vs necklaces',
    description: 'Commonly confused words: necklaced and necklaces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnecklaced\b/gi,
    message: 'Check: "necklaced" ("necklaced") vs "necklaces" ("necklaces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'necklaces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_needled_needles_2928',
    name: 'needled vs needles',
    description: 'Commonly confused words: needled and needles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneedled\b/gi,
    message: 'Check: "needled" ("needled") vs "needles" ("needles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'needles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_negated_negates_2929',
    name: 'negated vs negates',
    description: 'Commonly confused words: negated and negates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnegated\b/gi,
    message: 'Check: "negated" ("negated") vs "negates" ("negates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'negates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_negatived_negatives_2930',
    name: 'negatived vs negatives',
    description: 'Commonly confused words: negatived and negatives',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnegatived\b/gi,
    message: 'Check: "negatived" ("negatived") vs "negatives" ("negatives"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'negatives';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nerved_nerves_2931',
    name: 'nerved vs nerves',
    description: 'Commonly confused words: nerved and nerves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnerved\b/gi,
    message: 'Check: "nerved" ("nerved") vs "nerves" ("nerves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nerves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neuritic_neurotic_2932',
    name: 'neuritic vs neurotic',
    description: 'Commonly confused words: neuritic and neurotic',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneuritic\b/gi,
    message: 'Check: "neuritic" ("neuritic") vs "neurotic" ("neurotic"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'neurotic';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_neutralized_neutralizes_2933',
    name: 'neutralized vs neutralizes',
    description: 'Commonly confused words: neutralized and neutralizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bneutralized\b/gi,
    message: 'Check: "neutralized" ("neutralized") vs "neutralizes" ("neutralizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'neutralizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nibble_nobble_2934',
    name: 'nibble vs nobble',
    description: 'Commonly confused words: nibble and nobble',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnibble\b/gi,
    message: 'Check: "nibble" ("nibble") vs "nobble" ("nobble"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nobble';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nicker_bicker_2935',
    name: 'nicker vs bicker',
    description: 'Commonly confused words: nicker and bicker',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnicker\b/gi,
    message: 'Check: "nicker" ("nicker") vs "bicker" ("bicker"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bicker';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nicknamed_nicknames_2936',
    name: 'nicknamed vs nicknames',
    description: 'Commonly confused words: nicknamed and nicknames',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnicknamed\b/gi,
    message: 'Check: "nicknamed" ("nicknamed") vs "nicknames" ("nicknames"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nicknames';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nicks_micks_2937',
    name: 'nicks vs micks',
    description: 'Commonly confused words: nicks and micks',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnicks\b/gi,
    message: 'Check: "nicks" ("nicks") vs "micks" ("micks"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'micks';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nip_hip_2938',
    name: 'nip vs hip',
    description: 'Commonly confused words: nip and hip',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnip\b/gi,
    message: 'Check: "nip" ("nip") vs "hip" ("hip"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hip';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_niter_biter_2939',
    name: 'niter vs biter',
    description: 'Commonly confused words: niter and biter',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bniter\b/gi,
    message: 'Check: "niter" ("niter") vs "biter" ("biter"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'biter';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_niter_miter_2940',
    name: 'niter vs miter',
    description: 'Commonly confused words: niter and miter',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bniter\b/gi,
    message: 'Check: "niter" ("niter") vs "miter" ("miter"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'miter';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nitrated_nitrates_2941',
    name: 'nitrated vs nitrates',
    description: 'Commonly confused words: nitrated and nitrates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnitrated\b/gi,
    message: 'Check: "nitrated" ("nitrated") vs "nitrates" ("nitrates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nitrates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_node_bode_2942',
    name: 'node vs bode',
    description: 'Commonly confused words: node and bode',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnode\b/gi,
    message: 'Check: "node" ("node") vs "bode" ("bode"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bode';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nodes_bodes_2943',
    name: 'nodes vs bodes',
    description: 'Commonly confused words: nodes and bodes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnodes\b/gi,
    message: 'Check: "nodes" ("nodes") vs "bodes" ("bodes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bodes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nodes_modes_2944',
    name: 'nodes vs modes',
    description: 'Commonly confused words: nodes and modes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnodes\b/gi,
    message: 'Check: "nodes" ("nodes") vs "modes" ("modes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'modes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nods_bods_2945',
    name: 'nods vs bods',
    description: 'Commonly confused words: nods and bods',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnods\b/gi,
    message: 'Check: "nods" ("nods") vs "bods" ("bods"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bods';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nods_hods_2946',
    name: 'nods vs hods',
    description: 'Commonly confused words: nods and hods',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnods\b/gi,
    message: 'Check: "nods" ("nods") vs "hods" ("hods"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hods';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_noised_noises_2947',
    name: 'noised vs noises',
    description: 'Commonly confused words: noised and noises',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnoised\b/gi,
    message: 'Check: "noised" ("noised") vs "noises" ("noises"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'noises';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_none_bone_2948',
    name: 'none vs bone',
    description: 'Commonly confused words: none and bone',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnone\b/gi,
    message: 'Check: "none" ("none") vs "bone" ("bone"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bone';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_noon_boon_2949',
    name: 'noon vs boon',
    description: 'Commonly confused words: noon and boon',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnoon\b/gi,
    message: 'Check: "noon" ("noon") vs "boon" ("boon"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'boon';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_normalized_normalizes_2950',
    name: 'normalized vs normalizes',
    description: 'Commonly confused words: normalized and normalizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnormalized\b/gi,
    message: 'Check: "normalized" ("normalized") vs "normalizes" ("normalizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'normalizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nosed_hosed_2951',
    name: 'nosed vs hosed',
    description: 'Commonly confused words: nosed and hosed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnosed\b/gi,
    message: 'Check: "nosed" ("nosed") vs "hosed" ("hosed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hosed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nosed_noses_2952',
    name: 'nosed vs noses',
    description: 'Commonly confused words: nosed and noses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnosed\b/gi,
    message: 'Check: "nosed" ("nosed") vs "noses" ("noses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'noses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_noses_hoses_2953',
    name: 'noses vs hoses',
    description: 'Commonly confused words: noses and hoses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnoses\b/gi,
    message: 'Check: "noses" ("noses") vs "hoses" ("hoses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hoses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_notated_notates_2954',
    name: 'notated vs notates',
    description: 'Commonly confused words: notated and notates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnotated\b/gi,
    message: 'Check: "notated" ("notated") vs "notates" ("notates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'notates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_notched_notches_2955',
    name: 'notched vs notches',
    description: 'Commonly confused words: notched and notches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnotched\b/gi,
    message: 'Check: "notched" ("notched") vs "notches" ("notches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'notches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nourished_nourishes_2956',
    name: 'nourished vs nourishes',
    description: 'Commonly confused words: nourished and nourishes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnourished\b/gi,
    message: 'Check: "nourished" ("nourished") vs "nourishes" ("nourishes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nourishes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nuanced_nuances_2957',
    name: 'nuanced vs nuances',
    description: 'Commonly confused words: nuanced and nuances',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnuanced\b/gi,
    message: 'Check: "nuanced" ("nuanced") vs "nuances" ("nuances"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nuances';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nub_bub_2958',
    name: 'nub vs bub',
    description: 'Commonly confused words: nub and bub',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnub\b/gi,
    message: 'Check: "nub" ("nub") vs "bub" ("bub"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bub';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nubs_bubs_2959',
    name: 'nubs vs bubs',
    description: 'Commonly confused words: nubs and bubs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnubs\b/gi,
    message: 'Check: "nubs" ("nubs") vs "bubs" ("bubs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'bubs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nucleated_nucleates_2960',
    name: 'nucleated vs nucleates',
    description: 'Commonly confused words: nucleated and nucleates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnucleated\b/gi,
    message: 'Check: "nucleated" ("nucleated") vs "nucleates" ("nucleates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nucleates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nudged_budged_2961',
    name: 'nudged vs budged',
    description: 'Commonly confused words: nudged and budged',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnudged\b/gi,
    message: 'Check: "nudged" ("nudged") vs "budged" ("budged"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'budged';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nullified_nullifies_2962',
    name: 'nullified vs nullifies',
    description: 'Commonly confused words: nullified and nullifies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnullified\b/gi,
    message: 'Check: "nullified" ("nullified") vs "nullifies" ("nullifies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nullifies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nulls_hulls_2963',
    name: 'nulls vs hulls',
    description: 'Commonly confused words: nulls and hulls',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnulls\b/gi,
    message: 'Check: "nulls" ("nulls") vs "hulls" ("hulls"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'hulls';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nulls_mulls_2964',
    name: 'nulls vs mulls',
    description: 'Commonly confused words: nulls and mulls',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnulls\b/gi,
    message: 'Check: "nulls" ("nulls") vs "mulls" ("mulls"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'mulls';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nursed_nurses_2965',
    name: 'nursed vs nurses',
    description: 'Commonly confused words: nursed and nurses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnursed\b/gi,
    message: 'Check: "nursed" ("nursed") vs "nurses" ("nurses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nurses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_nuts_huts_2966',
    name: 'nuts vs huts',
    description: 'Commonly confused words: nuts and huts',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bnuts\b/gi,
    message: 'Check: "nuts" ("nuts") vs "huts" ("huts"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'huts';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
