/**
 * Auto-generated confusion rules (L)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.513Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesL: GrammarRule[] = [
  {
    id: 'confusion_lacks_lax_388',
    name: 'lacks vs lax',
    description: 'Commonly confused words: lacks and lax',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blacks\b/gi,
    message: 'Check: "lacks" ("lacks") vs "lax" ("lax"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lax';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_land_lend_389',
    name: 'land vs lend',
    description: 'Commonly confused words: land and lend',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bland\b/gi,
    message: 'Check: "land" ("land") vs "lend" ("lend"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lend';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lands_lends_390',
    name: 'lands vs lends',
    description: 'Commonly confused words: lands and lends',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blands\b/gi,
    message: 'Check: "lands" ("lands") vs "lends" ("lends"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lends';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_laps_lapse_391',
    name: 'laps vs lapse',
    description: 'Commonly confused words: laps and lapse',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blaps\b/gi,
    message: 'Check: "laps" ("laps") vs "lapse" ("lapse"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lapse';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lead_led_392',
    name: 'lead vs led',
    description: 'Commonly confused words: lead and led',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blead\b/gi,
    message: 'Check: "lead" (to guide (verb) or a metal (noun)) vs "led" (past tense of lead). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'led';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lean_lien_393',
    name: 'lean vs lien',
    description: 'Commonly confused words: lean and lien',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blean\b/gi,
    message: 'Check: "lean" ("lean") vs "lien" ("lien"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lien';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leans_liens_394',
    name: 'leans vs liens',
    description: 'Commonly confused words: leans and liens',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleans\b/gi,
    message: 'Check: "leans" ("leans") vs "liens" ("liens"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liens';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leased_least_395',
    name: 'leased vs least',
    description: 'Commonly confused words: leased and least',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleased\b/gi,
    message: 'Check: "leased" ("leased") vs "least" ("least"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'least';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leave_live_396',
    name: 'leave vs live',
    description: 'Commonly confused words: leave and live',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleave\b/gi,
    message: 'Did you mean "live"? "leave" ("leave") is often confused with "live" ("live").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'live';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_live_leave_397',
    name: 'live vs leave',
    description: 'Commonly confused words: live and leave',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blive\b/gi,
    message: 'Did you mean "leave"? "live" ("live") is often confused with "leave" ("leave").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leave';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leaved_left_398',
    name: 'leaved vs left',
    description: 'Commonly confused words: leaved and left',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleaved\b/gi,
    message: 'Check: "leaved" ("leaved") vs "left" ("left"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'left';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leaves_lives_399',
    name: 'leaves vs lives',
    description: 'Commonly confused words: leaves and lives',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleaves\b/gi,
    message: 'Did you mean "lives"? "leaves" ("leaves") is often confused with "lives" ("lives").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lives';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lives_leaves_400',
    name: 'lives vs leaves',
    description: 'Commonly confused words: lives and leaves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blives\b/gi,
    message: 'Did you mean "leaves"? "lives" ("lives") is often confused with "leaves" ("leaves").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leaves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lees_less_401',
    name: 'lees vs less',
    description: 'Commonly confused words: lees and less',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blees\b/gi,
    message: 'Check: "lees" ("lees") vs "less" ("less"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'less';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lends_lens_402',
    name: 'lends vs lens',
    description: 'Commonly confused words: lends and lens',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blends\b/gi,
    message: 'Check: "lends" ("lends") vs "lens" ("lens"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lens';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lessen_lesson_403',
    name: 'lessen vs lesson',
    description: 'Commonly confused words: lessen and lesson',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blessen\b/gi,
    message: 'Check: "lessen" ("lessen") vs "lesson" ("lesson"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lesson';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liable_libel_404',
    name: 'liable vs libel',
    description: 'Commonly confused words: liable and libel',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliable\b/gi,
    message: 'Check: "liable" ("liable") vs "libel" ("libel"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'libel';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liar_lyre_405',
    name: 'liar vs lyre',
    description: 'Commonly confused words: liar and lyre',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliar\b/gi,
    message: 'Check: "liar" ("liar") vs "lyre" ("lyre"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lyre';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lichen_liken_406',
    name: 'lichen vs liken',
    description: 'Commonly confused words: lichen and liken',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blichen\b/gi,
    message: 'Check: "lichen" ("lichen") vs "liken" ("liken"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liken';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lichens_likens_407',
    name: 'lichens vs likens',
    description: 'Commonly confused words: lichens and likens',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blichens\b/gi,
    message: 'Check: "lichens" ("lichens") vs "likens" ("likens"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'likens';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lieu_loo_408',
    name: 'lieu vs loo',
    description: 'Commonly confused words: lieu and loo',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blieu\b/gi,
    message: 'Check: "lieu" ("lieu") vs "loo" ("loo"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loo';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_life_live_409',
    name: 'life vs live',
    description: 'Commonly confused words: life and live',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blife\b/gi,
    message: 'Check: "life" ("life") vs "live" ("live"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'live';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limb_limn_410',
    name: 'limb vs limn',
    description: 'Commonly confused words: limb and limn',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimb\b/gi,
    message: 'Check: "limb" ("limb") vs "limn" ("limn"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limn';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limbs_limns_411',
    name: 'limbs vs limns',
    description: 'Commonly confused words: limbs and limns',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimbs\b/gi,
    message: 'Check: "limbs" ("limbs") vs "limns" ("limns"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limns';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_links_lynx_412',
    name: 'links vs lynx',
    description: 'Commonly confused words: links and lynx',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blinks\b/gi,
    message: 'Check: "links" ("links") vs "lynx" ("lynx"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lynx';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_literal_littoral_413',
    name: 'literal vs littoral',
    description: 'Commonly confused words: literal and littoral',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliteral\b/gi,
    message: 'Check: "literal" ("literal") vs "littoral" ("littoral"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'littoral';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_literals_littorals_414',
    name: 'literals vs littorals',
    description: 'Commonly confused words: literals and littorals',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliterals\b/gi,
    message: 'Check: "literals" ("literals") vs "littorals" ("littorals"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'littorals';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loan_lone_415',
    name: 'loan vs lone',
    description: 'Commonly confused words: loan and lone',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloan\b/gi,
    message: 'Check: "loan" ("loan") vs "lone" ("lone"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lone';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loch_lock_416',
    name: 'loch vs lock',
    description: 'Commonly confused words: loch and lock',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloch\b/gi,
    message: 'Check: "loch" ("loch") vs "lock" ("lock"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lock';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_locks_lox_417',
    name: 'locks vs lox',
    description: 'Commonly confused words: locks and lox',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blocks\b/gi,
    message: 'Check: "locks" ("locks") vs "lox" ("lox"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lox';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lode_lowed_418',
    name: 'lode vs lowed',
    description: 'Commonly confused words: lode and lowed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blode\b/gi,
    message: 'Check: "lode" ("lode") vs "lowed" ("lowed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lowed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lo_low_419',
    name: 'lo vs low',
    description: 'Commonly confused words: lo and low',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blo\b/gi,
    message: 'Check: "lo" ("lo") vs "low" ("low"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'low';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loose_lose_420',
    name: 'loose vs lose',
    description: 'Commonly confused words: loose and lose',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloose\b/gi,
    message: 'Check: "loose" (not tight (adjective)) vs "lose" (to misplace or fail to win (verb)). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lose';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loos_lose_421',
    name: 'loos vs lose',
    description: 'Commonly confused words: loos and lose',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloos\b/gi,
    message: 'Check: "loos" ("loos") vs "lose" (to misplace or fail to win (verb)). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lose';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loot_lute_422',
    name: 'loot vs lute',
    description: 'Commonly confused words: loot and lute',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloot\b/gi,
    message: 'Check: "loot" ("loot") vs "lute" ("lute"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lute';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lumbar_lumber_423',
    name: 'lumbar vs lumber',
    description: 'Commonly confused words: lumbar and lumber',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blumbar\b/gi,
    message: 'Check: "lumbar" ("lumbar") vs "lumber" ("lumber"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lumber';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_list_lost_786',
    name: 'list vs lost',
    description: 'Commonly confused words: list and lost',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blist\b/gi,
    message: 'Check: "list" ("list") vs "lost" ("lost"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lost';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_laced_laces_2678',
    name: 'laced vs laces',
    description: 'Commonly confused words: laced and laces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blaced\b/gi,
    message: 'Check: "laced" ("laced") vs "laces" ("laces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'laces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_laces_lades_2679',
    name: 'laces vs lades',
    description: 'Commonly confused words: laces and lades',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blaces\b/gi,
    message: 'Check: "laces" ("laces") vs "lades" ("lades"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lades';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lacing_lading_2680',
    name: 'lacing vs lading',
    description: 'Commonly confused words: lacing and lading',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blacing\b/gi,
    message: 'Check: "lacing" ("lacing") vs "lading" ("lading"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lading';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ladled_ladles_2681',
    name: 'ladled vs ladles',
    description: 'Commonly confused words: ladled and ladles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bladled\b/gi,
    message: 'Check: "ladled" ("ladled") vs "ladles" ("ladles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ladles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_laminae_laminar_2682',
    name: 'laminae vs laminar',
    description: 'Commonly confused words: laminae and laminar',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blaminae\b/gi,
    message: 'Check: "laminae" ("laminae") vs "laminar" ("laminar"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'laminar';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_laminated_laminates_2683',
    name: 'laminated vs laminates',
    description: 'Commonly confused words: laminated and laminates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blaminated\b/gi,
    message: 'Check: "laminated" ("laminated") vs "laminates" ("laminates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'laminates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lanced_lances_2684',
    name: 'lanced vs lances',
    description: 'Commonly confused words: lanced and lances',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blanced\b/gi,
    message: 'Check: "lanced" ("lanced") vs "lances" ("lances"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lances';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_landscaped_landscapes_2685',
    name: 'landscaped vs landscapes',
    description: 'Commonly confused words: landscaped and landscapes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blandscaped\b/gi,
    message: 'Check: "landscaped" ("landscaped") vs "landscapes" ("landscapes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'landscapes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_languished_languishes_2686',
    name: 'languished vs languishes',
    description: 'Commonly confused words: languished and languishes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blanguished\b/gi,
    message: 'Check: "languished" ("languished") vs "languishes" ("languishes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'languishes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lapsed_lapses_2687',
    name: 'lapsed vs lapses',
    description: 'Commonly confused words: lapsed and lapses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blapsed\b/gi,
    message: 'Check: "lapsed" ("lapsed") vs "lapses" ("lapses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lapses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lapsing_lapwing_2688',
    name: 'lapsing vs lapwing',
    description: 'Commonly confused words: lapsing and lapwing',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blapsing\b/gi,
    message: 'Check: "lapsing" ("lapsing") vs "lapwing" ("lapwing"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lapwing';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_larches_latches_2689',
    name: 'larches vs latches',
    description: 'Commonly confused words: larches and latches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blarches\b/gi,
    message: 'Check: "larches" ("larches") vs "latches" ("latches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'latches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_larch_latch_2690',
    name: 'larch vs latch',
    description: 'Commonly confused words: larch and latch',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blarch\b/gi,
    message: 'Check: "larch" ("larch") vs "latch" ("latch"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'latch';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lasing_lading_2691',
    name: 'lasing vs lading',
    description: 'Commonly confused words: lasing and lading',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blasing\b/gi,
    message: 'Check: "lasing" ("lasing") vs "lading" ("lading"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lading';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_latched_latches_2692',
    name: 'latched vs latches',
    description: 'Commonly confused words: latched and latches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blatched\b/gi,
    message: 'Check: "latched" ("latched") vs "latches" ("latches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'latches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lathed_lathes_2693',
    name: 'lathed vs lathes',
    description: 'Commonly confused words: lathed and lathes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blathed\b/gi,
    message: 'Check: "lathed" ("lathed") vs "lathes" ("lathes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lathes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_latticed_lattices_2694',
    name: 'latticed vs lattices',
    description: 'Commonly confused words: latticed and lattices',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blatticed\b/gi,
    message: 'Check: "latticed" ("latticed") vs "lattices" ("lattices"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lattices';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lava_lavs_2695',
    name: 'lava vs lavs',
    description: 'Commonly confused words: lava and lavs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blava\b/gi,
    message: 'Check: "lava" ("lava") vs "lavs" ("lavs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lavs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lavished_lavishes_2696',
    name: 'lavished vs lavishes',
    description: 'Commonly confused words: lavished and lavishes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blavished\b/gi,
    message: 'Check: "lavished" ("lavished") vs "lavishes" ("lavishes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lavishes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lavs_labs_2697',
    name: 'lavs vs labs',
    description: 'Commonly confused words: lavs and labs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blavs\b/gi,
    message: 'Check: "lavs" ("lavs") vs "labs" ("labs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'labs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leached_leaches_2698',
    name: 'leached vs leaches',
    description: 'Commonly confused words: leached and leaches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleached\b/gi,
    message: 'Check: "leached" ("leached") vs "leaches" ("leaches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leaches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leaded_leafed_2699',
    name: 'leaded vs leafed',
    description: 'Commonly confused words: leaded and leafed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleaded\b/gi,
    message: 'Check: "leaded" ("leaded") vs "leafed" ("leafed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leafed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leads_leafs_2700',
    name: 'leads vs leafs',
    description: 'Commonly confused words: leads and leafs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleads\b/gi,
    message: 'Check: "leads" ("leads") vs "leafs" ("leafs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leafs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leagued_leagues_2701',
    name: 'leagued vs leagues',
    description: 'Commonly confused words: leagued and leagues',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleagued\b/gi,
    message: 'Check: "leagued" ("leagued") vs "leagues" ("leagues"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leagues';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leased_leases_2702',
    name: 'leased vs leases',
    description: 'Commonly confused words: leased and leases',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleased\b/gi,
    message: 'Check: "leased" ("leased") vs "leases" ("leases"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leases';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leashed_leashes_2703',
    name: 'leashed vs leashes',
    description: 'Commonly confused words: leashed and leashes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleashed\b/gi,
    message: 'Check: "leashed" ("leashed") vs "leashes" ("leashes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leashes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leaves_leaved_2704',
    name: 'leaves vs leaved',
    description: 'Commonly confused words: leaves and leaved',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleaves\b/gi,
    message: 'Check: "leaves" ("leaves") vs "leaved" ("leaved"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leaved';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_leeched_leeches_2705',
    name: 'leeched vs leeches',
    description: 'Commonly confused words: leeched and leeches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bleeched\b/gi,
    message: 'Check: "leeched" ("leeched") vs "leeches" ("leeches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'leeches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_legislated_legislates_2706',
    name: 'legislated vs legislates',
    description: 'Commonly confused words: legislated and legislates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blegislated\b/gi,
    message: 'Check: "legislated" ("legislated") vs "legislates" ("legislates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'legislates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_legitimated_legitimates_2707',
    name: 'legitimated vs legitimates',
    description: 'Commonly confused words: legitimated and legitimates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blegitimated\b/gi,
    message: 'Check: "legitimated" ("legitimated") vs "legitimates" ("legitimates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'legitimates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_legitimized_legitimizes_2708',
    name: 'legitimized vs legitimizes',
    description: 'Commonly confused words: legitimized and legitimizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blegitimized\b/gi,
    message: 'Check: "legitimized" ("legitimized") vs "legitimizes" ("legitimizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'legitimizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lend_lens_2709',
    name: 'lend vs lens',
    description: 'Commonly confused words: lend and lens',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blend\b/gi,
    message: 'Check: "lend" ("lend") vs "lens" ("lens"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lens';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_levied_levies_2710',
    name: 'levied vs levies',
    description: 'Commonly confused words: levied and levies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blevied\b/gi,
    message: 'Check: "levied" ("levied") vs "levies" ("levies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'levies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_libation_ligation_2711',
    name: 'libation vs ligation',
    description: 'Commonly confused words: libation and ligation',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blibation\b/gi,
    message: 'Check: "libation" ("libation") vs "ligation" ("ligation"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ligation';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liberated_liberates_2712',
    name: 'liberated vs liberates',
    description: 'Commonly confused words: liberated and liberates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliberated\b/gi,
    message: 'Check: "liberated" ("liberated") vs "liberates" ("liberates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liberates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_licensed_licenses_2713',
    name: 'licensed vs licenses',
    description: 'Commonly confused words: licensed and licenses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blicensed\b/gi,
    message: 'Check: "licensed" ("licensed") vs "licenses" ("licenses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'licenses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_licked_lucked_2714',
    name: 'licked vs lucked',
    description: 'Commonly confused words: licked and lucked',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blicked\b/gi,
    message: 'Check: "licked" ("licked") vs "lucked" ("lucked"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lucked';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_licking_locking_2715',
    name: 'licking vs locking',
    description: 'Commonly confused words: licking and locking',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blicking\b/gi,
    message: 'Check: "licking" ("licking") vs "locking" ("locking"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'locking';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_licking_lucking_2716',
    name: 'licking vs lucking',
    description: 'Commonly confused words: licking and lucking',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blicking\b/gi,
    message: 'Check: "licking" ("licking") vs "lucking" ("lucking"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lucking';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lieder_liefer_2717',
    name: 'lieder vs liefer',
    description: 'Commonly confused words: lieder and liefer',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blieder\b/gi,
    message: 'Check: "lieder" ("lieder") vs "liefer" ("liefer"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liefer';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lifers_livers_2718',
    name: 'lifers vs livers',
    description: 'Commonly confused words: lifers and livers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blifers\b/gi,
    message: 'Check: "lifers" ("lifers") vs "livers" ("livers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'livers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ligated_ligates_2719',
    name: 'ligated vs ligates',
    description: 'Commonly confused words: ligated and ligates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bligated\b/gi,
    message: 'Check: "ligated" ("ligated") vs "ligates" ("ligates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ligates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ligatured_ligatures_2720',
    name: 'ligatured vs ligatures',
    description: 'Commonly confused words: ligatured and ligatures',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bligatured\b/gi,
    message: 'Check: "ligatured" ("ligatured") vs "ligatures" ("ligatures"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ligatures';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limbered_lumbered_2721',
    name: 'limbered vs lumbered',
    description: 'Commonly confused words: limbered and lumbered',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimbered\b/gi,
    message: 'Check: "limbered" ("limbered") vs "lumbered" ("lumbered"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lumbered';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limbers_lumbers_2722',
    name: 'limbers vs lumbers',
    description: 'Commonly confused words: limbers and lumbers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimbers\b/gi,
    message: 'Check: "limbers" ("limbers") vs "lumbers" ("lumbers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lumbers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limed_limes_2723',
    name: 'limed vs limes',
    description: 'Commonly confused words: limed and limes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimed\b/gi,
    message: 'Check: "limed" ("limed") vs "limes" ("limes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limed_lined_2724',
    name: 'limed vs lined',
    description: 'Commonly confused words: limed and lined',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimed\b/gi,
    message: 'Check: "limed" ("limed") vs "lined" ("lined"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lined';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liming_lining_2725',
    name: 'liming vs lining',
    description: 'Commonly confused words: liming and lining',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliming\b/gi,
    message: 'Check: "liming" ("liming") vs "lining" ("lining"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lining';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limos_limps_2726',
    name: 'limos vs limps',
    description: 'Commonly confused words: limos and limps',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimos\b/gi,
    message: 'Check: "limos" ("limos") vs "limps" ("limps"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limps';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limped_lumped_2727',
    name: 'limped vs lumped',
    description: 'Commonly confused words: limped and lumped',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimped\b/gi,
    message: 'Check: "limped" ("limped") vs "lumped" ("lumped"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lumped';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limper_limpet_2728',
    name: 'limper vs limpet',
    description: 'Commonly confused words: limper and limpet',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimper\b/gi,
    message: 'Check: "limper" ("limper") vs "limpet" ("limpet"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limpet';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_limping_lumping_2729',
    name: 'limping vs lumping',
    description: 'Commonly confused words: limping and lumping',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blimping\b/gi,
    message: 'Check: "limping" ("limping") vs "lumping" ("lumping"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lumping';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lined_lines_2730',
    name: 'lined vs lines',
    description: 'Commonly confused words: lined and lines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blined\b/gi,
    message: 'Check: "lined" ("lined") vs "lines" ("lines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_linger_longer_2731',
    name: 'linger vs longer',
    description: 'Commonly confused words: linger and longer',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blinger\b/gi,
    message: 'Check: "linger" ("linger") vs "longer" ("longer"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'longer';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lionized_lionizes_2732',
    name: 'lionized vs lionizes',
    description: 'Commonly confused words: lionized and lionizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blionized\b/gi,
    message: 'Check: "lionized" ("lionized") vs "lionizes" ("lionizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lionizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lipped_lopped_2733',
    name: 'lipped vs lopped',
    description: 'Commonly confused words: lipped and lopped',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blipped\b/gi,
    message: 'Check: "lipped" ("lipped") vs "lopped" ("lopped"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lopped';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liquefied_liquefies_2734',
    name: 'liquefied vs liquefies',
    description: 'Commonly confused words: liquefied and liquefies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliquefied\b/gi,
    message: 'Check: "liquefied" ("liquefied") vs "liquefies" ("liquefies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liquefies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_liquidated_liquidates_2735',
    name: 'liquidated vs liquidates',
    description: 'Commonly confused words: liquidated and liquidates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bliquidated\b/gi,
    message: 'Check: "liquidated" ("liquidated") vs "liquidates" ("liquidates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liquidates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lite_kite_2736',
    name: 'lite vs kite',
    description: 'Commonly confused words: lite and kite',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blite\b/gi,
    message: 'Check: "lite" ("lite") vs "kite" ("kite"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kite';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_livable_lovable_2737',
    name: 'livable vs lovable',
    description: 'Commonly confused words: livable and lovable',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blivable\b/gi,
    message: 'Check: "livable" ("livable") vs "lovable" ("lovable"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lovable';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lived_lives_2738',
    name: 'lived vs lives',
    description: 'Commonly confused words: lived and lives',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blived\b/gi,
    message: 'Check: "lived" ("lived") vs "lives" ("lives"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lives';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lobed_lobes_2739',
    name: 'lobed vs lobes',
    description: 'Commonly confused words: lobed and lobes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blobed\b/gi,
    message: 'Check: "lobed" ("lobed") vs "lobes" ("lobes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lobes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lobed_loved_2740',
    name: 'lobed vs loved',
    description: 'Commonly confused words: lobed and loved',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blobed\b/gi,
    message: 'Check: "lobed" ("lobed") vs "loved" ("loved"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loved';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lobes_loves_2741',
    name: 'lobes vs loves',
    description: 'Commonly confused words: lobes and loves',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blobes\b/gi,
    message: 'Check: "lobes" ("lobes") vs "loves" ("loves"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loves';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loci_lock_2742',
    name: 'loci vs lock',
    description: 'Commonly confused words: loci and lock',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloci\b/gi,
    message: 'Check: "loci" ("loci") vs "lock" ("lock"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lock';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loci_loco_2743',
    name: 'loci vs loco',
    description: 'Commonly confused words: loci and loco',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloci\b/gi,
    message: 'Check: "loci" ("loci") vs "loco" ("loco"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loco';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_locker_locket_2744',
    name: 'locker vs locket',
    description: 'Commonly confused words: locker and locket',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blocker\b/gi,
    message: 'Check: "locker" ("locker") vs "locket" ("locket"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'locket';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lodes_loses_2745',
    name: 'lodes vs loses',
    description: 'Commonly confused words: lodes and loses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blodes\b/gi,
    message: 'Check: "lodes" ("lodes") vs "loses" ("loses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loge_lobe_2746',
    name: 'loge vs lobe',
    description: 'Commonly confused words: loge and lobe',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloge\b/gi,
    message: 'Check: "loge" ("loge") vs "lobe" ("lobe"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lobe';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loiters_looters_2747',
    name: 'loiters vs looters',
    description: 'Commonly confused words: loiters and looters',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloiters\b/gi,
    message: 'Check: "loiters" ("loiters") vs "looters" ("looters"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'looters';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loner_liner_2748',
    name: 'loner vs liner',
    description: 'Commonly confused words: loner and liner',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloner\b/gi,
    message: 'Check: "loner" ("loner") vs "liner" ("liner"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'liner';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_longs_lings_2749',
    name: 'longs vs lings',
    description: 'Commonly confused words: longs and lings',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blongs\b/gi,
    message: 'Check: "longs" ("longs") vs "lings" ("lings"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lings';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loom_loon_2750',
    name: 'loom vs loon',
    description: 'Commonly confused words: loom and loon',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloom\b/gi,
    message: 'Check: "loom" ("loom") vs "loon" ("loon"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'loon';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_looped_lopped_2751',
    name: 'looped vs lopped',
    description: 'Commonly confused words: looped and lopped',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blooped\b/gi,
    message: 'Check: "looped" ("looped") vs "lopped" ("lopped"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lopped';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loosed_looses_2752',
    name: 'loosed vs looses',
    description: 'Commonly confused words: loosed and looses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloosed\b/gi,
    message: 'Check: "loosed" ("loosed") vs "looses" ("looses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'looses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_losers_lowers_2753',
    name: 'losers vs lowers',
    description: 'Commonly confused words: losers and lowers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blosers\b/gi,
    message: 'Check: "losers" ("losers") vs "lowers" ("lowers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lowers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lounged_lounges_2754',
    name: 'lounged vs lounges',
    description: 'Commonly confused words: lounged and lounges',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blounged\b/gi,
    message: 'Check: "lounged" ("lounged") vs "lounges" ("lounges"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lounges';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_loved_lived_2755',
    name: 'loved vs lived',
    description: 'Commonly confused words: loved and lived',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bloved\b/gi,
    message: 'Check: "loved" ("loved") vs "lived" ("lived"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lived';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lubricated_lubricates_2756',
    name: 'lubricated vs lubricates',
    description: 'Commonly confused words: lubricated and lubricates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blubricated\b/gi,
    message: 'Check: "lubricated" ("lubricated") vs "lubricates" ("lubricates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lubricates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lump_limp_2757',
    name: 'lump vs limp',
    description: 'Commonly confused words: lump and limp',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blump\b/gi,
    message: 'Check: "lump" ("lump") vs "limp" ("limp"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limp';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lumps_limps_2758',
    name: 'lumps vs limps',
    description: 'Commonly confused words: lumps and limps',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blumps\b/gi,
    message: 'Check: "lumps" ("lumps") vs "limps" ("limps"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'limps';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lunched_lunches_2759',
    name: 'lunched vs lunches',
    description: 'Commonly confused words: lunched and lunches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blunched\b/gi,
    message: 'Check: "lunched" ("lunched") vs "lunches" ("lunches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lunches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lunches_lynches_2760',
    name: 'lunches vs lynches',
    description: 'Commonly confused words: lunches and lynches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blunches\b/gi,
    message: 'Check: "lunches" ("lunches") vs "lynches" ("lynches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lynches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lunching_lynching_2761',
    name: 'lunching vs lynching',
    description: 'Commonly confused words: lunching and lynching',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blunching\b/gi,
    message: 'Check: "lunching" ("lunching") vs "lynching" ("lynching"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lynching';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lunch_lynch_2762',
    name: 'lunch vs lynch',
    description: 'Commonly confused words: lunch and lynch',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blunch\b/gi,
    message: 'Check: "lunch" ("lunch") vs "lynch" ("lynch"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lynch';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lungs_lings_2763',
    name: 'lungs vs lings',
    description: 'Commonly confused words: lungs and lings',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blungs\b/gi,
    message: 'Check: "lungs" ("lungs") vs "lings" ("lings"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lings';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lure_lire_2764',
    name: 'lure vs lire',
    description: 'Commonly confused words: lure and lire',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blure\b/gi,
    message: 'Check: "lure" ("lure") vs "lire" ("lire"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lire';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lusted_listed_2765',
    name: 'lusted vs listed',
    description: 'Commonly confused words: lusted and listed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blusted\b/gi,
    message: 'Check: "lusted" ("lusted") vs "listed" ("listed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'listed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lusted_ousted_2766',
    name: 'lusted vs ousted',
    description: 'Commonly confused words: lusted and ousted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blusted\b/gi,
    message: 'Check: "lusted" ("lusted") vs "ousted" ("ousted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ousted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lusting_ousting_2767',
    name: 'lusting vs ousting',
    description: 'Commonly confused words: lusting and ousting',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blusting\b/gi,
    message: 'Check: "lusting" ("lusting") vs "ousting" ("ousting"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ousting';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lusts_ousts_2768',
    name: 'lusts vs ousts',
    description: 'Commonly confused words: lusts and ousts',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blusts\b/gi,
    message: 'Check: "lusts" ("lusts") vs "ousts" ("ousts"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ousts';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lynched_lynches_2769',
    name: 'lynched vs lynches',
    description: 'Commonly confused words: lynched and lynches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blynched\b/gi,
    message: 'Check: "lynched" ("lynched") vs "lynches" ("lynches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lynches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_lyre_lure_2770',
    name: 'lyre vs lure',
    description: 'Commonly confused words: lyre and lure',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\blyre\b/gi,
    message: 'Check: "lyre" ("lyre") vs "lure" ("lure"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lure';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
