/**
 * Auto-generated confusion rules (O)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.515Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesO: GrammarRule[] = [
  {
    id: 'confusion_on_no_469',
    name: 'on vs no',
    description: 'Commonly confused words: on and no',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bon\b/gi,
    message: 'Did you mean "no"? "on" ("on") is often confused with "no" (negative).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'no';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oases_oasis_473',
    name: 'oases vs oasis',
    description: 'Commonly confused words: oases and oasis',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boases\b/gi,
    message: 'Check: "oases" ("oases") vs "oasis" ("oasis"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oasis';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oh_owe_474',
    name: 'oh vs owe',
    description: 'Commonly confused words: oh and owe',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boh\b/gi,
    message: 'Check: "oh" ("oh") vs "owe" ("owe"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'owe';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ohs_owes_475',
    name: 'ohs vs owes',
    description: 'Commonly confused words: ohs and owes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bohs\b/gi,
    message: 'Check: "ohs" ("ohs") vs "owes" ("owes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'owes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_on_one_476',
    name: 'on vs one',
    description: 'Commonly confused words: on and one',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bon\b/gi,
    message: 'Did you mean "one"? "on" ("on") is often confused with "one" ("one").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'one';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_one_on_477',
    name: 'one vs on',
    description: 'Commonly confused words: one and on',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bone\b/gi,
    message: 'Did you mean "on"? "one" ("one") is often confused with "on" ("on").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'on';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oohs_ooze_478',
    name: 'oohs vs ooze',
    description: 'Commonly confused words: oohs and ooze',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boohs\b/gi,
    message: 'Check: "oohs" ("oohs") vs "ooze" ("ooze"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ooze';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_or_ore_479',
    name: 'or vs ore',
    description: 'Commonly confused words: or and ore',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bor\b/gi,
    message: 'Did you mean "ore"? "or" ("or") is often confused with "ore" ("ore").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ore';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ore_or_480',
    name: 'ore vs or',
    description: 'Commonly confused words: ore and or',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bore\b/gi,
    message: 'Did you mean "or"? "ore" ("ore") is often confused with "or" ("or").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'or';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ours_outs_481',
    name: 'ours vs outs',
    description: 'Commonly confused words: ours and outs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bours\b/gi,
    message: 'Check: "ours" ("ours") vs "outs" ("outs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_out_put_482',
    name: 'out vs put',
    description: 'Commonly confused words: out and put',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bout\b/gi,
    message: 'Check: "out" ("out") vs "put" ("put"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'put';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overdo_overdue_483',
    name: 'overdo vs overdue',
    description: 'Commonly confused words: overdo and overdue',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverdo\b/gi,
    message: 'Check: "overdo" ("overdo") vs "overdue" ("overdue"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overdue';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overhead_overheard_484',
    name: 'overhead vs overheard',
    description: 'Commonly confused words: overhead and overheard',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverhead\b/gi,
    message: 'Check: "overhead" ("overhead") vs "overheard" ("overheard"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overheard';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_own_won_485',
    name: 'own vs won',
    description: 'Commonly confused words: own and won',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bown\b/gi,
    message: 'Did you mean "won"? "own" ("own") is often confused with "won" ("won").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'won';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_of_if_765',
    name: 'of vs if',
    description: 'Commonly confused words: of and if',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bof\b/gi,
    message: 'Did you mean "if"? "of" ("of") is often confused with "if" ("if").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'if';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oaf_oar_2967',
    name: 'oaf vs oar',
    description: 'Commonly confused words: oaf and oar',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boaf\b/gi,
    message: 'Check: "oaf" ("oaf") vs "oar" ("oar"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oar';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oafs_oars_2968',
    name: 'oafs vs oars',
    description: 'Commonly confused words: oafs and oars',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boafs\b/gi,
    message: 'Check: "oafs" ("oafs") vs "oars" ("oars"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oars';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oared_pared_2969',
    name: 'oared vs pared',
    description: 'Commonly confused words: oared and pared',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boared\b/gi,
    message: 'Check: "oared" ("oared") vs "pared" ("pared"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'pared';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oases_lases_2970',
    name: 'oases vs lases',
    description: 'Commonly confused words: oases and lases',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boases\b/gi,
    message: 'Check: "oases" ("oases") vs "lases" ("lases"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lases';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_objectified_objectifies_2971',
    name: 'objectified vs objectifies',
    description: 'Commonly confused words: objectified and objectifies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobjectified\b/gi,
    message: 'Check: "objectified" ("objectified") vs "objectifies" ("objectifies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'objectifies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_obligated_obligates_2972',
    name: 'obligated vs obligates',
    description: 'Commonly confused words: obligated and obligates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobligated\b/gi,
    message: 'Check: "obligated" ("obligated") vs "obligates" ("obligates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obligates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_obliterated_obliterates_2973',
    name: 'obliterated vs obliterates',
    description: 'Commonly confused words: obliterated and obliterates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobliterated\b/gi,
    message: 'Check: "obliterated" ("obliterated") vs "obliterates" ("obliterates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obliterates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_obscured_obscures_2974',
    name: 'obscured vs obscures',
    description: 'Commonly confused words: obscured and obscures',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobscured\b/gi,
    message: 'Check: "obscured" ("obscured") vs "obscures" ("obscures"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obscures';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_obsoleted_obsoletes_2975',
    name: 'obsoleted vs obsoletes',
    description: 'Commonly confused words: obsoleted and obsoletes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobsoleted\b/gi,
    message: 'Check: "obsoleted" ("obsoleted") vs "obsoletes" ("obsoletes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obsoletes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_obviated_obviates_2976',
    name: 'obviated vs obviates',
    description: 'Commonly confused words: obviated and obviates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bobviated\b/gi,
    message: 'Check: "obviated" ("obviated") vs "obviates" ("obviates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'obviates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_occluded_occludes_2977',
    name: 'occluded vs occludes',
    description: 'Commonly confused words: occluded and occludes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boccluded\b/gi,
    message: 'Check: "occluded" ("occluded") vs "occludes" ("occludes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'occludes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_occupied_occupies_2978',
    name: 'occupied vs occupies',
    description: 'Commonly confused words: occupied and occupies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boccupied\b/gi,
    message: 'Check: "occupied" ("occupied") vs "occupies" ("occupies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'occupies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ocular_ovular_2979',
    name: 'ocular vs ovular',
    description: 'Commonly confused words: ocular and ovular',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bocular\b/gi,
    message: 'Check: "ocular" ("ocular") vs "ovular" ("ovular"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ovular';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_officiated_officiates_2980',
    name: 'officiated vs officiates',
    description: 'Commonly confused words: officiated and officiates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bofficiated\b/gi,
    message: 'Check: "officiated" ("officiated") vs "officiates" ("officiates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'officiates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oiled_piled_2981',
    name: 'oiled vs piled',
    description: 'Commonly confused words: oiled and piled',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boiled\b/gi,
    message: 'Check: "oiled" ("oiled") vs "piled" ("piled"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'piled';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oiling_piling_2982',
    name: 'oiling vs piling',
    description: 'Commonly confused words: oiling and piling',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boiling\b/gi,
    message: 'Check: "oiling" ("oiling") vs "piling" ("piling"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'piling';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oily_lily_2983',
    name: 'oily vs lily',
    description: 'Commonly confused words: oily and lily',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boily\b/gi,
    message: 'Check: "oily" ("oily") vs "lily" ("lily"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lily';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oops_lops_2984',
    name: 'oops vs lops',
    description: 'Commonly confused words: oops and lops',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boops\b/gi,
    message: 'Check: "oops" ("oops") vs "lops" ("lops"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lops';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_operated_operates_2985',
    name: 'operated vs operates',
    description: 'Commonly confused words: operated and operates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boperated\b/gi,
    message: 'Check: "operated" ("operated") vs "operates" ("operates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'operates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oppressed_oppresses_2986',
    name: 'oppressed vs oppresses',
    description: 'Commonly confused words: oppressed and oppresses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boppressed\b/gi,
    message: 'Check: "oppressed" ("oppressed") vs "oppresses" ("oppresses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oppresses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_orientated_orientates_2987',
    name: 'orientated vs orientates',
    description: 'Commonly confused words: orientated and orientates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\borientated\b/gi,
    message: 'Check: "orientated" ("orientated") vs "orientates" ("orientates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'orientates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_ostracized_ostracizes_2988',
    name: 'ostracized vs ostracizes',
    description: 'Commonly confused words: ostracized and ostracizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bostracized\b/gi,
    message: 'Check: "ostracized" ("ostracized") vs "ostracizes" ("ostracizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ostracizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oust_lust_2989',
    name: 'oust vs lust',
    description: 'Commonly confused words: oust and lust',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boust\b/gi,
    message: 'Check: "oust" ("oust") vs "lust" ("lust"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lust';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outclassed_outclasses_2990',
    name: 'outclassed vs outclasses',
    description: 'Commonly confused words: outclassed and outclasses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutclassed\b/gi,
    message: 'Check: "outclassed" ("outclassed") vs "outclasses" ("outclasses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outclasses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outfight_outright_2991',
    name: 'outfight vs outright',
    description: 'Commonly confused words: outfight and outright',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutfight\b/gi,
    message: 'Check: "outfight" ("outfight") vs "outright" ("outright"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outright';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outlined_outlines_2992',
    name: 'outlined vs outlines',
    description: 'Commonly confused words: outlined and outlines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutlined\b/gi,
    message: 'Check: "outlined" ("outlined") vs "outlines" ("outlines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outlines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outpaced_outpaces_2993',
    name: 'outpaced vs outpaces',
    description: 'Commonly confused words: outpaced and outpaces',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutpaced\b/gi,
    message: 'Check: "outpaced" ("outpaced") vs "outpaces" ("outpaces"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outpaces';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outreached_outreaches_2994',
    name: 'outreached vs outreaches',
    description: 'Commonly confused words: outreached and outreaches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutreached\b/gi,
    message: 'Check: "outreached" ("outreached") vs "outreaches" ("outreaches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outreaches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outshine_outshone_2995',
    name: 'outshine vs outshone',
    description: 'Commonly confused words: outshine and outshone',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutshine\b/gi,
    message: 'Check: "outshine" ("outshine") vs "outshone" ("outshone"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outshone';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_outsourced_outsources_2996',
    name: 'outsourced vs outsources',
    description: 'Commonly confused words: outsourced and outsources',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boutsourced\b/gi,
    message: 'Check: "outsourced" ("outsourced") vs "outsources" ("outsources"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'outsources';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overcharged_overcharges_2997',
    name: 'overcharged vs overcharges',
    description: 'Commonly confused words: overcharged and overcharges',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bovercharged\b/gi,
    message: 'Check: "overcharged" ("overcharged") vs "overcharges" ("overcharges"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overcharges';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overemphasized_overemphasizes_2998',
    name: 'overemphasized vs overemphasizes',
    description: 'Commonly confused words: overemphasized and overemphasizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boveremphasized\b/gi,
    message: 'Check: "overemphasized" ("overemphasized") vs "overemphasizes" ("overemphasizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overemphasizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overestimated_overestimates_2999',
    name: 'overestimated vs overestimates',
    description: 'Commonly confused words: overestimated and overestimates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverestimated\b/gi,
    message: 'Check: "overestimated" ("overestimated") vs "overestimates" ("overestimates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overestimates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overhearing_overheating_3000',
    name: 'overhearing vs overheating',
    description: 'Commonly confused words: overhearing and overheating',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverhearing\b/gi,
    message: 'Check: "overhearing" ("overhearing") vs "overheating" ("overheating"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overheating';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overhear_overheat_3001',
    name: 'overhear vs overheat',
    description: 'Commonly confused words: overhear and overheat',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverhear\b/gi,
    message: 'Check: "overhear" ("overhear") vs "overheat" ("overheat"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overheat';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overhears_overheats_3002',
    name: 'overhears vs overheats',
    description: 'Commonly confused words: overhears and overheats',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverhears\b/gi,
    message: 'Check: "overhears" ("overhears") vs "overheats" ("overheats"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overheats';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overreached_overreaches_3003',
    name: 'overreached vs overreaches',
    description: 'Commonly confused words: overreached and overreaches',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverreached\b/gi,
    message: 'Check: "overreached" ("overreached") vs "overreaches" ("overreaches"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overreaches';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_override_overrode_3004',
    name: 'override vs overrode',
    description: 'Commonly confused words: override and overrode',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverride\b/gi,
    message: 'Check: "override" ("override") vs "overrode" ("overrode"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overrode';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overruled_overrules_3005',
    name: 'overruled vs overrules',
    description: 'Commonly confused words: overruled and overrules',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverruled\b/gi,
    message: 'Check: "overruled" ("overruled") vs "overrules" ("overrules"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overrules';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oversimplified_oversimplifies_3006',
    name: 'oversimplified vs oversimplifies',
    description: 'Commonly confused words: oversimplified and oversimplifies',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boversimplified\b/gi,
    message: 'Check: "oversimplified" ("oversimplified") vs "oversimplifies" ("oversimplifies"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oversimplifies';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overstated_overstates_3007',
    name: 'overstated vs overstates',
    description: 'Commonly confused words: overstated and overstates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverstated\b/gi,
    message: 'Check: "overstated" ("overstated") vs "overstates" ("overstates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overstates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overstated_overstayed_3008',
    name: 'overstated vs overstayed',
    description: 'Commonly confused words: overstated and overstayed',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverstated\b/gi,
    message: 'Check: "overstated" ("overstated") vs "overstayed" ("overstayed"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overstayed';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overstating_overstaying_3009',
    name: 'overstating vs overstaying',
    description: 'Commonly confused words: overstating and overstaying',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverstating\b/gi,
    message: 'Check: "overstating" ("overstating") vs "overstaying" ("overstaying"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overstaying';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_overused_overuses_3010',
    name: 'overused vs overuses',
    description: 'Commonly confused words: overused and overuses',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boverused\b/gi,
    message: 'Check: "overused" ("overused") vs "overuses" ("overuses"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'overuses';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_owns_pwns_3011',
    name: 'owns vs pwns',
    description: 'Commonly confused words: owns and pwns',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bowns\b/gi,
    message: 'Check: "owns" ("owns") vs "pwns" ("pwns"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'pwns';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oxidized_oxidizes_3012',
    name: 'oxidized vs oxidizes',
    description: 'Commonly confused words: oxidized and oxidizes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boxidized\b/gi,
    message: 'Check: "oxidized" ("oxidized") vs "oxidizes" ("oxidizes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oxidizes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oxygenated_oxygenates_3013',
    name: 'oxygenated vs oxygenates',
    description: 'Commonly confused words: oxygenated and oxygenates',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boxygenated\b/gi,
    message: 'Check: "oxygenated" ("oxygenated") vs "oxygenates" ("oxygenates"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'oxygenates';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_oyster_ouster_3014',
    name: 'oyster vs ouster',
    description: 'Commonly confused words: oyster and ouster',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\boyster\b/gi,
    message: 'Check: "oyster" ("oyster") vs "ouster" ("ouster"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'ouster';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
