/**
 * Auto-generated confusion rules (K)
 * Source: LanguageTool confusion_sets.txt
 * Generated: 2026-01-28T19:51:36.512Z
 * 
 * These rules detect commonly confused word pairs like:
 * - affect/effect
 * - their/there/they're
 * - accept/except
 * etc.
 * 
 * DO NOT EDIT - Generated by convert-confusion-sets.cjs
 */

import type { GrammarRule } from '../../../types';

export const confusionRulesK: GrammarRule[] = [
  {
    id: 'confusion_kind_king_374',
    name: 'kind vs king',
    description: 'Commonly confused words: kind and king',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkind\b/gi,
    message: 'Check: "kind" ("kind") vs "king" ("king"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'king';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kinds_kings_375',
    name: 'kinds vs kings',
    description: 'Commonly confused words: kinds and kings',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkinds\b/gi,
    message: 'Check: "kinds" ("kinds") vs "kings" ("kings"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kings';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knead_need_376',
    name: 'knead vs need',
    description: 'Commonly confused words: knead and need',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknead\b/gi,
    message: 'Check: "knead" ("knead") vs "need" ("need"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'need';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kneads_needs_377',
    name: 'kneads vs needs',
    description: 'Commonly confused words: kneads and needs',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkneads\b/gi,
    message: 'Check: "kneads" ("kneads") vs "needs" ("needs"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'needs';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knew_new_378',
    name: 'knew vs new',
    description: 'Commonly confused words: knew and new',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknew\b/gi,
    message: 'Check: "knew" (past tense of know) vs "new" (not old). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'new';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knight_night_379',
    name: 'knight vs night',
    description: 'Commonly confused words: knight and night',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknight\b/gi,
    message: 'Check: "knight" ("knight") vs "night" ("night"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'night';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knows_noes_380',
    name: 'knows vs noes',
    description: 'Commonly confused words: knows and noes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknows\b/gi,
    message: 'Check: "knows" ("knows") vs "noes" ("noes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'noes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knows_nose_381',
    name: 'knows vs nose',
    description: 'Commonly confused words: knows and nose',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknows\b/gi,
    message: 'Did you mean "nose"? "knows" ("knows") is often confused with "nose" ("nose").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'nose';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_know_no_383',
    name: 'know vs no',
    description: 'Commonly confused words: know and no',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknow\b/gi,
    message: 'Did you mean "no"? "know" (to understand) is often confused with "no" (negative).',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'no';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_know_known_385',
    name: 'know vs known',
    description: 'Commonly confused words: know and known',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknow\b/gi,
    message: 'Did you mean "known"? "know" (to understand) is often confused with "known" ("known").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'known';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_know_now_386',
    name: 'know vs now',
    description: 'Commonly confused words: know and now',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknow\b/gi,
    message: 'Did you mean "now"? "know" (to understand) is often confused with "now" ("now").',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'now';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_keynoted_keynotes_2664',
    name: 'keynoted vs keynotes',
    description: 'Commonly confused words: keynoted and keynotes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkeynoted\b/gi,
    message: 'Check: "keynoted" ("keynoted") vs "keynotes" ("keynotes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'keynotes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kidded_lidded_2665',
    name: 'kidded vs lidded',
    description: 'Commonly confused words: kidded and lidded',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkidded\b/gi,
    message: 'Check: "kidded" ("kidded") vs "lidded" ("lidded"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'lidded';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kikes_likes_2666',
    name: 'kikes vs likes',
    description: 'Commonly confused words: kikes and likes',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkikes\b/gi,
    message: 'Check: "kikes" ("kikes") vs "likes" ("likes"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'likes';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kilos_kills_2667',
    name: 'kilos vs kills',
    description: 'Commonly confused words: kilos and kills',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkilos\b/gi,
    message: 'Check: "kilos" ("kilos") vs "kills" ("kills"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kills';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kinda_kinds_2668',
    name: 'kinda vs kinds',
    description: 'Commonly confused words: kinda and kinds',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkinda\b/gi,
    message: 'Check: "kinda" ("kinda") vs "kinds" ("kinds"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kinds';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kindled_kindles_2669',
    name: 'kindled vs kindles',
    description: 'Commonly confused words: kindled and kindles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkindled\b/gi,
    message: 'Check: "kindled" ("kindled") vs "kindles" ("kindles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kindles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kinds_kines_2670',
    name: 'kinds vs kines',
    description: 'Commonly confused words: kinds and kines',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkinds\b/gi,
    message: 'Check: "kinds" ("kinds") vs "kines" ("kines"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'kines';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_kinking_linking_2671',
    name: 'kinking vs linking',
    description: 'Commonly confused words: kinking and linking',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bkinking\b/gi,
    message: 'Check: "kinking" ("kinking") vs "linking" ("linking"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'linking';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knee_knew_2672',
    name: 'knee vs knew',
    description: 'Commonly confused words: knee and knew',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknee\b/gi,
    message: 'Check: "knee" ("knee") vs "knew" (past tense of know). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knew';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knickers_knockers_2673',
    name: 'knickers vs knockers',
    description: 'Commonly confused words: knickers and knockers',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknickers\b/gi,
    message: 'Check: "knickers" ("knickers") vs "knockers" ("knockers"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knockers';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knit_knot_2674',
    name: 'knit vs knot',
    description: 'Commonly confused words: knit and knot',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknit\b/gi,
    message: 'Check: "knit" ("knit") vs "knot" ("knot"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knot';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knits_knots_2675',
    name: 'knits vs knots',
    description: 'Commonly confused words: knits and knots',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknits\b/gi,
    message: 'Check: "knits" ("knits") vs "knots" ("knots"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knots';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knitted_knotted_2676',
    name: 'knitted vs knotted',
    description: 'Commonly confused words: knitted and knotted',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknitted\b/gi,
    message: 'Check: "knitted" ("knitted") vs "knotted" ("knotted"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knotted';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  },
  {
    id: 'confusion_knuckled_knuckles_2677',
    name: 'knuckled vs knuckles',
    description: 'Commonly confused words: knuckled and knuckles',
    category: 'confusion',
    severity: 'warning' as const,
    pattern: /\bknuckled\b/gi,
    message: 'Check: "knuckled" ("knuckled") vs "knuckles" ("knuckles"). These words are often confused.',
    suggestions: (match: RegExpMatchArray) => {
      // Preserve case
      const orig = match[0];
      let replacement = 'knuckles';
      if (orig[0] === orig[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      if (orig === orig.toUpperCase()) {
        replacement = replacement.toUpperCase();
      }
      return [replacement];
    },
  }
];
